// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MicroTage(
  input         clock,
  input         reset,
  input         io_stageCtrl_s0_fire,
  input  [48:0] io_startPc_addr,
  input         io_fastTrain_valid,
  input  [48:0] io_fastTrain_bits_startPc_addr,
  input  [4:0]  io_fastTrain_bits_finalPrediction_cfiPosition,
  input  [1:0]  io_fastTrain_bits_finalPrediction_attribute_branchType,
  input         io_fastTrain_bits_finalPrediction_taken,
  input         io_fastTrain_bits_hasOverride,
  input         io_fastTrain_bits_utageMeta_histTableHitMap_0,
  input         io_fastTrain_bits_utageMeta_histTableHitMap_1,
  input         io_fastTrain_bits_utageMeta_histTableTakenMap_0,
  input         io_fastTrain_bits_utageMeta_histTableTakenMap_1,
  input  [1:0]  io_fastTrain_bits_utageMeta_histTableUsefulVec_0,
  input  [1:0]  io_fastTrain_bits_utageMeta_histTableUsefulVec_1,
  input  [4:0]  io_fastTrain_bits_utageMeta_histTableCfiPositionVec_0,
  input  [4:0]  io_fastTrain_bits_utageMeta_histTableCfiPositionVec_1,
  input         io_fastTrain_bits_utageMeta_baseTaken,
  input  [4:0]  io_fastTrain_bits_utageMeta_baseCfiPosition,
  input  [11:0] io_foldedPathHist_hist_11_foldedHist,
  input  [10:0] io_foldedPathHist_hist_10_foldedHist,
  input  [8:0]  io_foldedPathHist_hist_9_foldedHist,
  input  [8:0]  io_foldedPathHist_hist_4_foldedHist,
  input  [7:0]  io_foldedPathHist_hist_3_foldedHist,
  input  [11:0] io_foldedPathHistForTrain_hist_11_foldedHist,
  input  [10:0] io_foldedPathHistForTrain_hist_10_foldedHist,
  input  [8:0]  io_foldedPathHistForTrain_hist_9_foldedHist,
  input  [8:0]  io_foldedPathHistForTrain_hist_4_foldedHist,
  input  [7:0]  io_foldedPathHistForTrain_hist_3_foldedHist,
  input         io_abtbPrediction_0_valid,
  input  [4:0]  io_abtbPrediction_0_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_0_bits_attribute_branchType,
  input         io_abtbPrediction_0_bits_taken,
  input         io_abtbPrediction_1_valid,
  input  [4:0]  io_abtbPrediction_1_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_1_bits_attribute_branchType,
  input         io_abtbPrediction_1_bits_taken,
  input         io_abtbPrediction_2_valid,
  input  [4:0]  io_abtbPrediction_2_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_2_bits_attribute_branchType,
  input         io_abtbPrediction_2_bits_taken,
  input         io_abtbPrediction_3_valid,
  input  [4:0]  io_abtbPrediction_3_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_3_bits_attribute_branchType,
  input         io_abtbPrediction_3_bits_taken,
  input         io_abtbPrediction_4_valid,
  input  [4:0]  io_abtbPrediction_4_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_4_bits_attribute_branchType,
  input         io_abtbPrediction_4_bits_taken,
  input         io_abtbPrediction_5_valid,
  input  [4:0]  io_abtbPrediction_5_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_5_bits_attribute_branchType,
  input         io_abtbPrediction_5_bits_taken,
  input         io_abtbPrediction_6_valid,
  input  [4:0]  io_abtbPrediction_6_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_6_bits_attribute_branchType,
  input         io_abtbPrediction_6_bits_taken,
  input         io_abtbPrediction_7_valid,
  input  [4:0]  io_abtbPrediction_7_bits_cfiPosition,
  input  [1:0]  io_abtbPrediction_7_bits_attribute_branchType,
  input         io_abtbPrediction_7_bits_taken,
  output        io_prediction_valid,
  output        io_prediction_bits_taken,
  output [4:0]  io_prediction_bits_cfiPosition,
  output        io_meta_bits_histTableHitMap_0,
  output        io_meta_bits_histTableHitMap_1,
  output        io_meta_bits_histTableTakenMap_0,
  output        io_meta_bits_histTableTakenMap_1,
  output [1:0]  io_meta_bits_histTableUsefulVec_0,
  output [1:0]  io_meta_bits_histTableUsefulVec_1,
  output [4:0]  io_meta_bits_histTableCfiPositionVec_0,
  output [4:0]  io_meta_bits_histTableCfiPositionVec_1,
  output        io_meta_bits_baseTaken,
  output [4:0]  io_meta_bits_baseCfiPosition
);

  wire        t0_histHitMisPred;
  wire        _MicroTageTable_1_io_resp_valid;
  wire        _MicroTageTable_1_io_resp_bits_taken;
  wire [4:0]  _MicroTageTable_1_io_resp_bits_cfiPosition;
  wire [1:0]  _MicroTageTable_1_io_resp_bits_useful;
  wire [2:0]  _MicroTageTable_1_io_resp_bits_hitTakenCtr_value;
  wire        _MicroTageTable_io_resp_valid;
  wire        _MicroTageTable_io_resp_bits_taken;
  wire [4:0]  _MicroTageTable_io_resp_bits_cfiPosition;
  wire [1:0]  _MicroTageTable_io_resp_bits_useful;
  wire [2:0]  _MicroTageTable_io_resp_bits_hitTakenCtr_value;
  reg  [9:0]  lowTickCounter;
  reg  [11:0] highTickCounter;
  reg         s1_meta_bits_histTableHitMap_0;
  reg         s1_meta_bits_histTableHitMap_1;
  reg         s1_meta_bits_histTableTakenMap_0;
  reg         s1_meta_bits_histTableTakenMap_1;
  reg  [1:0]  s1_meta_bits_histTableUsefulVec_0;
  reg  [1:0]  s1_meta_bits_histTableUsefulVec_1;
  reg  [4:0]  s1_meta_bits_histTableCfiPositionVec_0;
  reg  [4:0]  s1_meta_bits_histTableCfiPositionVec_1;
  reg         s1_meta_bits_baseTaken;
  reg  [4:0]  s1_meta_bits_baseCfiPosition;
  reg         io_prediction_r_valid;
  reg         io_prediction_r_bits_taken;
  reg  [4:0]  io_prediction_r_bits_cfiPosition;
  wire        t0_predTaken =
    io_fastTrain_bits_utageMeta_histTableHitMap_1
      ? io_fastTrain_bits_utageMeta_histTableTakenMap_1
      : io_fastTrain_bits_utageMeta_histTableHitMap_0
        & io_fastTrain_bits_utageMeta_histTableTakenMap_0;
  wire [4:0]  t0_predCfiPosition =
    io_fastTrain_bits_utageMeta_histTableHitMap_1
      ? io_fastTrain_bits_utageMeta_histTableCfiPositionVec_1
      : io_fastTrain_bits_utageMeta_histTableHitMap_0
          ? io_fastTrain_bits_utageMeta_histTableCfiPositionVec_0
          : 5'h0;
  wire        t0_predHit =
    io_fastTrain_bits_utageMeta_histTableHitMap_0
    | io_fastTrain_bits_utageMeta_histTableHitMap_1;
  wire        _fastTrainHasPredBr_T_2 =
    io_fastTrain_bits_finalPrediction_attribute_branchType == 2'h1;
  assign t0_histHitMisPred =
    t0_predHit
    & (io_fastTrain_bits_finalPrediction_attribute_branchType != 2'h1 & t0_predTaken
       | _fastTrainHasPredBr_T_2
       & (t0_predTaken != io_fastTrain_bits_finalPrediction_taken
          | t0_predCfiPosition != io_fastTrain_bits_finalPrediction_cfiPosition));
  wire        _GEN =
    ~t0_predHit & _fastTrainHasPredBr_T_2 & io_fastTrain_bits_finalPrediction_taken
    & io_fastTrain_valid & io_fastTrain_bits_hasOverride;
  wire        _GEN_0 = (t0_histHitMisPred | _GEN) & io_fastTrain_valid;
  wire        _GEN_1 = t0_predHit & io_fastTrain_valid;
  wire        positionEQ =
    t0_predCfiPosition == io_fastTrain_bits_finalPrediction_cfiPosition;
  wire        t0_updateTaken =
    positionEQ & io_fastTrain_bits_finalPrediction_taken & _fastTrainHasPredBr_T_2;
  wire        t0_actualTaken =
    _fastTrainHasPredBr_T_2 & io_fastTrain_bits_finalPrediction_taken;
  wire [4:0]  t0_actualCfiPosition =
    _fastTrainHasPredBr_T_2
      ? io_fastTrain_bits_finalPrediction_cfiPosition
      : t0_predCfiPosition;
  wire [1:0]  t0_providerMask_enc =
    io_fastTrain_bits_utageMeta_histTableHitMap_1
      ? 2'h1
      : {io_fastTrain_bits_utageMeta_histTableHitMap_0, 1'h0};
  wire [1:0]  t0_fastAllocMask =
    {t0_providerMask_enc[0], t0_providerMask_enc[1]}
    & {io_fastTrain_bits_utageMeta_histTableUsefulVec_1 == 2'h0,
       io_fastTrain_bits_utageMeta_histTableUsefulVec_0 == 2'h0};
  wire [1:0]  hitMask =
    {io_fastTrain_bits_utageMeta_histTableHitMap_1,
     io_fastTrain_bits_utageMeta_histTableHitMap_0};
  wire [1:0]  allocCandidateMask =
    ~((hitMask == 2'h0
         ? 2'h0
         : hitMask
           | 2'({io_fastTrain_bits_utageMeta_histTableHitMap_1,
                 io_fastTrain_bits_utageMeta_histTableHitMap_0} - 2'h1))
      | {io_fastTrain_bits_utageMeta_histTableUsefulVec_1[1],
         io_fastTrain_bits_utageMeta_histTableUsefulVec_0[1]});
  wire [1:0]  t0_allocMask =
    (|t0_fastAllocMask)
      ? t0_fastAllocMask
      : allocCandidateMask[0] ? 2'h1 : {allocCandidateMask[1], 1'h0};
  wire        positionLT =
    t0_predCfiPosition < io_fastTrain_bits_finalPrediction_cfiPosition;
  wire        fastTrainHasPredBr =
    positionEQ | positionLT
    & io_fastTrain_bits_finalPrediction_attribute_branchType != 2'h1;
  wire        MicroTageTable_io_update_bits_allocValid = t0_allocMask[0] & _GEN_0;
  wire        _GEN_2 = t0_providerMask_enc[1] & _GEN_1;
  wire        _GEN_3 =
    t0_histHitMisPred
    | (io_fastTrain_bits_utageMeta_baseCfiPosition == t0_predCfiPosition
       & (io_fastTrain_bits_utageMeta_baseTaken ^ t0_predTaken)
       | io_fastTrain_bits_utageMeta_baseCfiPosition < t0_predCfiPosition
       & (~io_fastTrain_bits_utageMeta_baseTaken & t0_predTaken
          | io_fastTrain_bits_utageMeta_baseTaken)
       | io_fastTrain_bits_utageMeta_baseCfiPosition > t0_predCfiPosition
       & (~io_fastTrain_bits_utageMeta_baseTaken & t0_predTaken
          | io_fastTrain_bits_utageMeta_baseTaken & t0_predTaken)) & fastTrainHasPredBr;
  wire        MicroTageTable_1_io_update_bits_allocValid = t0_allocMask[1] & _GEN_0;
  wire        _GEN_4 = t0_providerMask_enc[0] & _GEN_1;
  wire        _GEN_5 = io_fastTrain_valid & t0_histHitMisPred;
  wire        _GEN_6 = _GEN_5 & positionLT;
  wire        _GEN_7 =
    _GEN_5 & t0_predCfiPosition > io_fastTrain_bits_finalPrediction_cfiPosition;
  wire        _GEN_8 = _GEN_5 & positionEQ;
  wire [2:0]  choseTableTakenCtr_value =
    _MicroTageTable_1_io_resp_valid
      ? _MicroTageTable_1_io_resp_bits_hitTakenCtr_value
      : _MicroTageTable_io_resp_valid
          ? _MicroTageTable_io_resp_bits_hitTakenCtr_value
          : 3'h0;
  wire        s1_abtbCondTakenMask_0 =
    io_abtbPrediction_0_valid & io_abtbPrediction_0_bits_taken
    & io_abtbPrediction_0_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_1 =
    io_abtbPrediction_1_valid & io_abtbPrediction_1_bits_taken
    & io_abtbPrediction_1_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_2 =
    io_abtbPrediction_2_valid & io_abtbPrediction_2_bits_taken
    & io_abtbPrediction_2_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_3 =
    io_abtbPrediction_3_valid & io_abtbPrediction_3_bits_taken
    & io_abtbPrediction_3_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_4 =
    io_abtbPrediction_4_valid & io_abtbPrediction_4_bits_taken
    & io_abtbPrediction_4_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_5 =
    io_abtbPrediction_5_valid & io_abtbPrediction_5_bits_taken
    & io_abtbPrediction_5_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_6 =
    io_abtbPrediction_6_valid & io_abtbPrediction_6_bits_taken
    & io_abtbPrediction_6_bits_attribute_branchType == 2'h1;
  wire        s1_abtbCondTakenMask_7 =
    io_abtbPrediction_7_valid & io_abtbPrediction_7_bits_taken
    & io_abtbPrediction_7_bits_attribute_branchType == 2'h1;
  wire        _GEN_9 = t0_allocMask == 2'h0 & _GEN_0;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      lowTickCounter <= 10'h0;
      highTickCounter <= 12'h0;
      s1_meta_bits_histTableHitMap_0 <= 1'h0;
      s1_meta_bits_histTableHitMap_1 <= 1'h0;
      s1_meta_bits_histTableTakenMap_0 <= 1'h0;
      s1_meta_bits_histTableTakenMap_1 <= 1'h0;
      s1_meta_bits_histTableUsefulVec_0 <= 2'h0;
      s1_meta_bits_histTableUsefulVec_1 <= 2'h0;
      s1_meta_bits_histTableCfiPositionVec_0 <= 5'h0;
      s1_meta_bits_histTableCfiPositionVec_1 <= 5'h0;
      s1_meta_bits_baseTaken <= 1'h0;
      s1_meta_bits_baseCfiPosition <= 5'h0;
      io_prediction_r_valid <= 1'h0;
      io_prediction_r_bits_taken <= 1'h0;
      io_prediction_r_bits_cfiPosition <= 5'h0;
    end
    else begin
      if (lowTickCounter[9])
        lowTickCounter <= 10'h0;
      else if (_GEN_9)
        lowTickCounter <= 10'(lowTickCounter + 10'h1);
      if (highTickCounter[11])
        highTickCounter <= 12'h0;
      else if (_GEN_9)
        highTickCounter <= 12'(highTickCounter + 12'h1);
      if (io_stageCtrl_s0_fire) begin
        s1_meta_bits_histTableHitMap_0 <= _MicroTageTable_io_resp_valid;
        s1_meta_bits_histTableHitMap_1 <= _MicroTageTable_1_io_resp_valid;
        s1_meta_bits_histTableTakenMap_0 <= _MicroTageTable_io_resp_bits_taken;
        s1_meta_bits_histTableTakenMap_1 <= _MicroTageTable_1_io_resp_bits_taken;
        s1_meta_bits_histTableUsefulVec_0 <= _MicroTageTable_io_resp_bits_useful;
        s1_meta_bits_histTableUsefulVec_1 <= _MicroTageTable_1_io_resp_bits_useful;
        s1_meta_bits_histTableCfiPositionVec_0 <=
          _MicroTageTable_io_resp_bits_cfiPosition;
        s1_meta_bits_histTableCfiPositionVec_1 <=
          _MicroTageTable_1_io_resp_bits_cfiPosition;
        io_prediction_r_valid <=
          (_MicroTageTable_io_resp_valid | _MicroTageTable_1_io_resp_valid)
          & ((&choseTableTakenCtr_value) | choseTableTakenCtr_value == 3'h0);
        io_prediction_r_bits_taken <=
          (_MicroTageTable_1_io_resp_valid
             ? _MicroTageTable_1_io_resp_bits_taken
             : _MicroTageTable_io_resp_valid & _MicroTageTable_io_resp_bits_taken)
          & (&choseTableTakenCtr_value);
        io_prediction_r_bits_cfiPosition <=
          _MicroTageTable_1_io_resp_valid
            ? _MicroTageTable_1_io_resp_bits_cfiPosition
            : _MicroTageTable_io_resp_valid
                ? _MicroTageTable_io_resp_bits_cfiPosition
                : 5'h0;
      end
      s1_meta_bits_baseTaken <=
        s1_abtbCondTakenMask_0 | s1_abtbCondTakenMask_1 | s1_abtbCondTakenMask_2
        | s1_abtbCondTakenMask_3 | s1_abtbCondTakenMask_4 | s1_abtbCondTakenMask_5
        | s1_abtbCondTakenMask_6 | s1_abtbCondTakenMask_7;
      s1_meta_bits_baseCfiPosition <=
        (s1_abtbCondTakenMask_0
         & (~s1_abtbCondTakenMask_1
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_1_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_2
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_2_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_3
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_3_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_4
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_4_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_5
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_5_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_6
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
         & (~s1_abtbCondTakenMask_7
            | io_abtbPrediction_0_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
           ? io_abtbPrediction_0_bits_cfiPosition
           : 5'h0)
        | (s1_abtbCondTakenMask_1
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_1_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_2_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_3_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_1_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_1_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_2
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_2_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_2_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_2_bits_cfiPosition < io_abtbPrediction_3_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_2_bits_cfiPosition < io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_2_bits_cfiPosition < io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_2_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_2_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_2_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_3
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_3_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_3_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_2_bits_cfiPosition >= io_abtbPrediction_3_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_3_bits_cfiPosition < io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_3_bits_cfiPosition < io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_3_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_3_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_3_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_4
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_2_bits_cfiPosition >= io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_3_bits_cfiPosition >= io_abtbPrediction_4_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_4_bits_cfiPosition < io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_4_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_4_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_4_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_5
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_2_bits_cfiPosition >= io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_3_bits_cfiPosition >= io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_4_bits_cfiPosition >= io_abtbPrediction_5_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_5_bits_cfiPosition < io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_5_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_5_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_6
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_2_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_3_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_4_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_5_bits_cfiPosition >= io_abtbPrediction_6_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_7
              | io_abtbPrediction_6_bits_cfiPosition < io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_6_bits_cfiPosition
             : 5'h0)
        | (s1_abtbCondTakenMask_7
           & (~s1_abtbCondTakenMask_0
              | io_abtbPrediction_0_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_1
              | io_abtbPrediction_1_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_2
              | io_abtbPrediction_2_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_3
              | io_abtbPrediction_3_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_4
              | io_abtbPrediction_4_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_5
              | io_abtbPrediction_5_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
           & (~s1_abtbCondTakenMask_6
              | io_abtbPrediction_6_bits_cfiPosition >= io_abtbPrediction_7_bits_cfiPosition)
             ? io_abtbPrediction_7_bits_cfiPosition
             : 5'h0);
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        lowTickCounter = _RANDOM[1'h0][9:0];
        highTickCounter = _RANDOM[1'h0][21:10];
        s1_meta_bits_histTableHitMap_0 = _RANDOM[1'h0][23];
        s1_meta_bits_histTableHitMap_1 = _RANDOM[1'h0][24];
        s1_meta_bits_histTableTakenMap_0 = _RANDOM[1'h0][25];
        s1_meta_bits_histTableTakenMap_1 = _RANDOM[1'h0][26];
        s1_meta_bits_histTableUsefulVec_0 = _RANDOM[1'h0][28:27];
        s1_meta_bits_histTableUsefulVec_1 = _RANDOM[1'h0][30:29];
        s1_meta_bits_histTableCfiPositionVec_0 = {_RANDOM[1'h0][31], _RANDOM[1'h1][3:0]};
        s1_meta_bits_histTableCfiPositionVec_1 = _RANDOM[1'h1][8:4];
        s1_meta_bits_baseTaken = _RANDOM[1'h1][9];
        s1_meta_bits_baseCfiPosition = _RANDOM[1'h1][14:10];
        io_prediction_r_valid = _RANDOM[1'h1][15];
        io_prediction_r_bits_taken = _RANDOM[1'h1][16];
        io_prediction_r_bits_cfiPosition = _RANDOM[1'h1][21:17];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        lowTickCounter = 10'h0;
        highTickCounter = 12'h0;
        s1_meta_bits_histTableHitMap_0 = 1'h0;
        s1_meta_bits_histTableHitMap_1 = 1'h0;
        s1_meta_bits_histTableTakenMap_0 = 1'h0;
        s1_meta_bits_histTableTakenMap_1 = 1'h0;
        s1_meta_bits_histTableUsefulVec_0 = 2'h0;
        s1_meta_bits_histTableUsefulVec_1 = 2'h0;
        s1_meta_bits_histTableCfiPositionVec_0 = 5'h0;
        s1_meta_bits_histTableCfiPositionVec_1 = 5'h0;
        s1_meta_bits_baseTaken = 1'h0;
        s1_meta_bits_baseCfiPosition = 5'h0;
        io_prediction_r_valid = 1'h0;
        io_prediction_r_bits_taken = 1'h0;
        io_prediction_r_bits_cfiPosition = 5'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MicroTageTable MicroTageTable (
    .clock                                                   (clock),
    .reset                                                   (reset),
    .io_req_startPc_addr                                     (io_startPc_addr),
    .io_req_foldedPathHist_hist_4_foldedHist
      (io_foldedPathHist_hist_4_foldedHist),
    .io_req_foldedPathHist_hist_3_foldedHist
      (io_foldedPathHist_hist_3_foldedHist),
    .io_resp_valid
      (_MicroTageTable_io_resp_valid),
    .io_resp_bits_taken
      (_MicroTageTable_io_resp_bits_taken),
    .io_resp_bits_cfiPosition
      (_MicroTageTable_io_resp_bits_cfiPosition),
    .io_resp_bits_useful
      (_MicroTageTable_io_resp_bits_useful),
    .io_resp_bits_hitTakenCtr_value
      (_MicroTageTable_io_resp_bits_hitTakenCtr_value),
    .io_update_valid
      (io_fastTrain_valid & (MicroTageTable_io_update_bits_allocValid | _GEN_2)),
    .io_update_bits_startPc_addr
      (io_fastTrain_bits_startPc_addr),
    .io_update_bits_allocValid
      (MicroTageTable_io_update_bits_allocValid),
    .io_update_bits_updateValid
      (_GEN_2 & fastTrainHasPredBr),
    .io_update_bits_usefulValid                              (_GEN_2 & _GEN_3),
    .io_update_bits_allocTaken                               (t0_actualTaken),
    .io_update_bits_allocCfiPosition                         (t0_actualCfiPosition),
    .io_update_bits_updateTaken                              (t0_updateTaken),
    .io_update_bits_updateCfiPosition                        (t0_predCfiPosition),
    .io_update_bits_usefulCorrect                            (~t0_histHitMisPred),
    .io_update_bits_foldedPathHistForTrain_hist_4_foldedHist
      (io_foldedPathHistForTrain_hist_4_foldedHist),
    .io_update_bits_foldedPathHistForTrain_hist_3_foldedHist
      (io_foldedPathHistForTrain_hist_3_foldedHist),
    .io_usefulReset                                          (lowTickCounter[9])
  );
  MicroTageTable_1 MicroTageTable_1 (
    .clock                                                    (clock),
    .reset                                                    (reset),
    .io_req_startPc_addr                                      (io_startPc_addr),
    .io_req_foldedPathHist_hist_11_foldedHist
      (io_foldedPathHist_hist_11_foldedHist),
    .io_req_foldedPathHist_hist_10_foldedHist
      (io_foldedPathHist_hist_10_foldedHist),
    .io_req_foldedPathHist_hist_9_foldedHist
      (io_foldedPathHist_hist_9_foldedHist),
    .io_resp_valid
      (_MicroTageTable_1_io_resp_valid),
    .io_resp_bits_taken
      (_MicroTageTable_1_io_resp_bits_taken),
    .io_resp_bits_cfiPosition
      (_MicroTageTable_1_io_resp_bits_cfiPosition),
    .io_resp_bits_useful
      (_MicroTageTable_1_io_resp_bits_useful),
    .io_resp_bits_hitTakenCtr_value
      (_MicroTageTable_1_io_resp_bits_hitTakenCtr_value),
    .io_update_valid
      (io_fastTrain_valid & (MicroTageTable_1_io_update_bits_allocValid | _GEN_4)),
    .io_update_bits_startPc_addr
      (io_fastTrain_bits_startPc_addr),
    .io_update_bits_allocValid
      (MicroTageTable_1_io_update_bits_allocValid),
    .io_update_bits_updateValid
      (_GEN_4 & fastTrainHasPredBr),
    .io_update_bits_usefulValid                               (_GEN_4 & _GEN_3),
    .io_update_bits_allocTaken                                (t0_actualTaken),
    .io_update_bits_allocCfiPosition                          (t0_actualCfiPosition),
    .io_update_bits_updateTaken                               (t0_updateTaken),
    .io_update_bits_updateCfiPosition                         (t0_predCfiPosition),
    .io_update_bits_usefulCorrect                             (~t0_histHitMisPred),
    .io_update_bits_foldedPathHistForTrain_hist_11_foldedHist
      (io_foldedPathHistForTrain_hist_11_foldedHist),
    .io_update_bits_foldedPathHistForTrain_hist_10_foldedHist
      (io_foldedPathHistForTrain_hist_10_foldedHist),
    .io_update_bits_foldedPathHistForTrain_hist_9_foldedHist
      (io_foldedPathHistForTrain_hist_9_foldedHist),
    .io_usefulReset                                           (highTickCounter[11])
  );
  assign io_prediction_valid = io_prediction_r_valid;
  assign io_prediction_bits_taken = io_prediction_r_bits_taken;
  assign io_prediction_bits_cfiPosition = io_prediction_r_bits_cfiPosition;
  assign io_meta_bits_histTableHitMap_0 = s1_meta_bits_histTableHitMap_0;
  assign io_meta_bits_histTableHitMap_1 = s1_meta_bits_histTableHitMap_1;
  assign io_meta_bits_histTableTakenMap_0 = s1_meta_bits_histTableTakenMap_0;
  assign io_meta_bits_histTableTakenMap_1 = s1_meta_bits_histTableTakenMap_1;
  assign io_meta_bits_histTableUsefulVec_0 = s1_meta_bits_histTableUsefulVec_0;
  assign io_meta_bits_histTableUsefulVec_1 = s1_meta_bits_histTableUsefulVec_1;
  assign io_meta_bits_histTableCfiPositionVec_0 = s1_meta_bits_histTableCfiPositionVec_0;
  assign io_meta_bits_histTableCfiPositionVec_1 = s1_meta_bits_histTableCfiPositionVec_1;
  assign io_meta_bits_baseTaken = s1_meta_bits_baseTaken;
  assign io_meta_bits_baseCfiPosition = s1_meta_bits_baseCfiPosition;
endmodule

