// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module WriteBuffer_12(
  input         clock,
  input         reset,
  output        io_write_0_ready,
  input         io_write_0_valid,
  input  [8:0]  io_write_0_bits_setIdx,
  input         io_write_0_bits_entry_valid,
  input  [12:0] io_write_0_bits_entry_tag,
  input  [2:0]  io_write_0_bits_entry_takenCtr_value,
  input  [1:0]  io_write_0_bits_usefulCtr_value,
  output        io_write_1_ready,
  input         io_write_1_valid,
  input  [8:0]  io_write_1_bits_setIdx,
  input         io_write_1_bits_entry_valid,
  input  [12:0] io_write_1_bits_entry_tag,
  input  [2:0]  io_write_1_bits_entry_takenCtr_value,
  input  [1:0]  io_write_1_bits_usefulCtr_value,
  input         io_read_0_ready,
  output        io_read_0_valid,
  output [8:0]  io_read_0_bits_setIdx,
  output        io_read_0_bits_entry_valid,
  output [12:0] io_read_0_bits_entry_tag,
  output [2:0]  io_read_0_bits_entry_takenCtr_value,
  output [1:0]  io_read_0_bits_usefulCtr_value,
  input         io_read_1_ready,
  output        io_read_1_valid,
  output [8:0]  io_read_1_bits_setIdx,
  output        io_read_1_bits_entry_valid,
  output [12:0] io_read_1_bits_entry_tag,
  output [2:0]  io_read_1_bits_entry_takenCtr_value,
  output [1:0]  io_read_1_bits_usefulCtr_value,
  input         io_takenMask_0,
  input         io_takenMask_1
);

  wire             io_read_1_ready_probe = io_read_1_ready;
  wire             io_read_0_ready_probe = io_read_0_ready;
  reg              needWrite_0_0;
  wire             readValidVec_0_0 = needWrite_0_0;
  reg              needWrite_0_1;
  wire             readValidVec_0_1 = needWrite_0_1;
  reg              needWrite_0_2;
  wire             readValidVec_0_2 = needWrite_0_2;
  reg              needWrite_0_3;
  wire             readValidVec_0_3 = needWrite_0_3;
  reg              needWrite_1_0;
  wire             readValidVec_1_0 = needWrite_1_0;
  reg              needWrite_1_1;
  wire             readValidVec_1_1 = needWrite_1_1;
  reg              needWrite_1_2;
  wire             readValidVec_1_2 = needWrite_1_2;
  reg              needWrite_1_3;
  wire             readValidVec_1_3 = needWrite_1_3;
  reg  [8:0]       entries_0_0_setIdx;
  reg              entries_0_0_entry_valid;
  reg  [12:0]      entries_0_0_entry_tag;
  reg  [2:0]       entries_0_0_entry_takenCtr_value;
  reg  [1:0]       entries_0_0_usefulCtr_value;
  reg  [8:0]       entries_0_1_setIdx;
  reg              entries_0_1_entry_valid;
  reg  [12:0]      entries_0_1_entry_tag;
  reg  [2:0]       entries_0_1_entry_takenCtr_value;
  reg  [1:0]       entries_0_1_usefulCtr_value;
  reg  [8:0]       entries_0_2_setIdx;
  reg              entries_0_2_entry_valid;
  reg  [12:0]      entries_0_2_entry_tag;
  reg  [2:0]       entries_0_2_entry_takenCtr_value;
  reg  [1:0]       entries_0_2_usefulCtr_value;
  reg  [8:0]       entries_0_3_setIdx;
  reg              entries_0_3_entry_valid;
  reg  [12:0]      entries_0_3_entry_tag;
  reg  [2:0]       entries_0_3_entry_takenCtr_value;
  reg  [1:0]       entries_0_3_usefulCtr_value;
  reg  [8:0]       entries_1_0_setIdx;
  reg              entries_1_0_entry_valid;
  reg  [12:0]      entries_1_0_entry_tag;
  reg  [2:0]       entries_1_0_entry_takenCtr_value;
  reg  [1:0]       entries_1_0_usefulCtr_value;
  reg  [8:0]       entries_1_1_setIdx;
  reg              entries_1_1_entry_valid;
  reg  [12:0]      entries_1_1_entry_tag;
  reg  [2:0]       entries_1_1_entry_takenCtr_value;
  reg  [1:0]       entries_1_1_usefulCtr_value;
  reg  [8:0]       entries_1_2_setIdx;
  reg              entries_1_2_entry_valid;
  reg  [12:0]      entries_1_2_entry_tag;
  reg  [2:0]       entries_1_2_entry_takenCtr_value;
  reg  [1:0]       entries_1_2_usefulCtr_value;
  reg  [8:0]       entries_1_3_setIdx;
  reg              entries_1_3_entry_valid;
  reg  [12:0]      entries_1_3_entry_tag;
  reg  [2:0]       entries_1_3_entry_takenCtr_value;
  reg  [1:0]       entries_1_3_usefulCtr_value;
  reg              valids_0_0;
  reg              valids_0_1;
  reg              valids_0_2;
  reg              valids_0_3;
  reg              valids_1_0;
  reg              valids_1_1;
  reg              valids_1_2;
  reg              valids_1_3;
  wire             _hitMask_0_0_T = io_write_0_valid & valids_0_0;
  wire             _hitMask_0_0_T_1 = io_write_0_bits_setIdx == entries_0_0_setIdx;
  wire             setIdxHitVec_0 = _hitMask_0_0_T & _hitMask_0_0_T_1;
  wire             _hitMask_0_1_T = io_write_0_valid & valids_0_1;
  wire             _hitMask_0_1_T_1 = io_write_0_bits_setIdx == entries_0_1_setIdx;
  wire             setIdxHitVec_1 = _hitMask_0_1_T & _hitMask_0_1_T_1;
  wire             _hitMask_0_2_T = io_write_0_valid & valids_0_2;
  wire             _hitMask_0_2_T_1 = io_write_0_bits_setIdx == entries_0_2_setIdx;
  wire             setIdxHitVec_2 = _hitMask_0_2_T & _hitMask_0_2_T_1;
  wire             _hitMask_0_3_T = io_write_0_valid & valids_0_3;
  wire             _hitMask_0_3_T_1 = io_write_0_bits_setIdx == entries_0_3_setIdx;
  wire             setIdxHitVec_3 = _hitMask_0_3_T & _hitMask_0_3_T_1;
  wire [2:0]       _GEN =
    3'({1'h0, 2'({1'h0, setIdxHitVec_0} + {1'h0, setIdxHitVec_1})}
       + {1'h0, 2'({1'h0, setIdxHitVec_2} + {1'h0, setIdxHitVec_3})});
  wire             _GEN_0 = io_write_0_valid & (|(_GEN[2:1]));
  wire             _hitMask_1_0_T_5 = io_write_1_valid & valids_1_0;
  wire             _hitMask_1_0_T_6 = io_write_1_bits_setIdx == entries_1_0_setIdx;
  wire             setIdxHitVec_0_1 = _hitMask_1_0_T_5 & _hitMask_1_0_T_6;
  wire             _hitMask_1_1_T_5 = io_write_1_valid & valids_1_1;
  wire             _hitMask_1_1_T_6 = io_write_1_bits_setIdx == entries_1_1_setIdx;
  wire             setIdxHitVec_1_1 = _hitMask_1_1_T_5 & _hitMask_1_1_T_6;
  wire             _hitMask_1_2_T_5 = io_write_1_valid & valids_1_2;
  wire             _hitMask_1_2_T_6 = io_write_1_bits_setIdx == entries_1_2_setIdx;
  wire             setIdxHitVec_2_1 = _hitMask_1_2_T_5 & _hitMask_1_2_T_6;
  wire             _hitMask_1_3_T_5 = io_write_1_valid & valids_1_3;
  wire             _hitMask_1_3_T_6 = io_write_1_bits_setIdx == entries_1_3_setIdx;
  wire             setIdxHitVec_3_1 = _hitMask_1_3_T_5 & _hitMask_1_3_T_6;
  wire [2:0]       _GEN_1 =
    3'({1'h0, 2'({1'h0, setIdxHitVec_0_1} + {1'h0, setIdxHitVec_1_1})}
       + {1'h0, 2'({1'h0, setIdxHitVec_2_1} + {1'h0, setIdxHitVec_3_1})});
  wire             _GEN_2 = io_write_1_valid & (|(_GEN_1[2:1]));
  wire             writeSameEntry_probe =
    io_write_0_valid & io_write_1_valid & io_write_0_bits_setIdx == io_write_1_bits_setIdx
    & io_write_0_bits_entry_tag == io_write_1_bits_entry_tag;
  wire             hitMask_0_0 =
    _hitMask_0_0_T & _hitMask_0_0_T_1
    & io_write_0_bits_entry_tag == entries_0_0_entry_tag;
  wire             hitMask_0_1 =
    _hitMask_0_1_T & _hitMask_0_1_T_1
    & io_write_0_bits_entry_tag == entries_0_1_entry_tag;
  wire             hitMask_0_2 =
    _hitMask_0_2_T & _hitMask_0_2_T_1
    & io_write_0_bits_entry_tag == entries_0_2_entry_tag;
  wire             hitMask_0_3 =
    _hitMask_0_3_T & _hitMask_0_3_T_1
    & io_write_0_bits_entry_tag == entries_0_3_entry_tag;
  wire             hitMask_1_0 =
    io_write_0_valid & valids_1_0 & io_write_0_bits_setIdx == entries_1_0_setIdx
    & io_write_0_bits_entry_tag == entries_1_0_entry_tag;
  wire             hitMask_1_1 =
    io_write_0_valid & valids_1_1 & io_write_0_bits_setIdx == entries_1_1_setIdx
    & io_write_0_bits_entry_tag == entries_1_1_entry_tag;
  wire             hitMask_1_2 =
    io_write_0_valid & valids_1_2 & io_write_0_bits_setIdx == entries_1_2_setIdx
    & io_write_0_bits_entry_tag == entries_1_2_entry_tag;
  wire             hitMask_1_3 =
    io_write_0_valid & valids_1_3 & io_write_0_bits_setIdx == entries_1_3_setIdx
    & io_write_0_bits_entry_tag == entries_1_3_entry_tag;
  wire [3:0]       _GEN_3 =
    4'({1'h0,
        3'({1'h0, 2'({1'h0, hitMask_0_0} + {1'h0, hitMask_0_1})}
           + {1'h0, 2'({1'h0, hitMask_0_2} + {1'h0, hitMask_0_3})})}
       + {1'h0,
          3'({1'h0, 2'({1'h0, hitMask_1_0} + {1'h0, hitMask_1_1})}
             + {1'h0, 2'({1'h0, hitMask_1_2} + {1'h0, hitMask_1_3})})});
  wire             _GEN_4 = io_write_0_valid & (|(_GEN_3[3:1]));
  wire             _hitRowsVec_T = hitMask_0_0 | hitMask_0_1;
  wire             hit =
    _hitRowsVec_T | hitMask_0_2 | hitMask_0_3 | hitMask_1_0 | hitMask_1_1 | hitMask_1_2
    | hitMask_1_3;
  wire             hitRowsVec_0 = _hitRowsVec_T | hitMask_0_2 | hitMask_0_3;
  wire             rowIdx = hitMask_1_0 | hitMask_1_1 | hitMask_1_2 | hitMask_1_3;
  wire [1:0]       hitRowIdxVec_0 =
    {|{hitMask_0_3, hitMask_0_2}, hitMask_0_3 | hitMask_0_1};
  wire [1:0]       hitRowIdxVec_1 =
    {|{hitMask_1_3, hitMask_1_2}, hitMask_1_3 | hitMask_1_1};
  wire [1:0]       _GEN_5 = rowIdx ? hitRowIdxVec_1 : hitRowIdxVec_0;
  wire [3:0]       _GEN_6 =
    {{needWrite_1_3}, {needWrite_1_2}, {needWrite_1_1}, {needWrite_1_0}};
  wire [3:0]       _GEN_7 =
    {{needWrite_0_3}, {needWrite_0_2}, {needWrite_0_1}, {needWrite_0_0}};
  wire [3:0]       _GEN_8 = rowIdx ? _GEN_6 : _GEN_7;
  wire             hitNotWritten = hit & _GEN_8[_GEN_5];
  wire             hitWritten = hit & ~_GEN_8[_GEN_5];
  wire             _GEN_9 = io_write_0_valid & ~hit;
  wire [3:0][8:0]  _GEN_10 =
    {{entries_1_3_setIdx},
     {entries_1_2_setIdx},
     {entries_1_1_setIdx},
     {entries_1_0_setIdx}};
  wire [3:0][8:0]  _GEN_11 =
    {{entries_0_3_setIdx},
     {entries_0_2_setIdx},
     {entries_0_1_setIdx},
     {entries_0_0_setIdx}};
  wire [3:0]       _GEN_12 =
    {{entries_1_3_entry_valid},
     {entries_1_2_entry_valid},
     {entries_1_1_entry_valid},
     {entries_1_0_entry_valid}};
  wire [3:0]       _GEN_13 =
    {{entries_0_3_entry_valid},
     {entries_0_2_entry_valid},
     {entries_0_1_entry_valid},
     {entries_0_0_entry_valid}};
  wire [3:0][12:0] _GEN_14 =
    {{entries_1_3_entry_tag},
     {entries_1_2_entry_tag},
     {entries_1_1_entry_tag},
     {entries_1_0_entry_tag}};
  wire [3:0][12:0] _GEN_15 =
    {{entries_0_3_entry_tag},
     {entries_0_2_entry_tag},
     {entries_0_1_entry_tag},
     {entries_0_0_entry_tag}};
  wire [3:0][2:0]  _GEN_16 =
    {{entries_1_3_entry_takenCtr_value},
     {entries_1_2_entry_takenCtr_value},
     {entries_1_1_entry_takenCtr_value},
     {entries_1_0_entry_takenCtr_value}};
  wire [3:0][2:0]  _GEN_17 =
    {{entries_0_3_entry_takenCtr_value},
     {entries_0_2_entry_takenCtr_value},
     {entries_0_1_entry_takenCtr_value},
     {entries_0_0_entry_takenCtr_value}};
  wire [3:0][1:0]  _GEN_18 =
    {{entries_1_3_usefulCtr_value},
     {entries_1_2_usefulCtr_value},
     {entries_1_1_usefulCtr_value},
     {entries_1_0_usefulCtr_value}};
  wire [3:0][1:0]  _GEN_19 =
    {{entries_0_3_usefulCtr_value},
     {entries_0_2_usefulCtr_value},
     {entries_0_1_usefulCtr_value},
     {entries_0_0_usefulCtr_value}};
  wire             _GEN_20 = io_write_0_valid & hitNotWritten;
  wire             _GEN_21 = io_write_0_valid & hitWritten;
  wire             _GEN_22 = io_write_0_valid & hit;
  wire             hitMask_1_0_0 =
    io_write_1_valid & valids_0_0 & io_write_1_bits_setIdx == entries_0_0_setIdx
    & io_write_1_bits_entry_tag == entries_0_0_entry_tag;
  wire             hitMask_1_0_1 =
    io_write_1_valid & valids_0_1 & io_write_1_bits_setIdx == entries_0_1_setIdx
    & io_write_1_bits_entry_tag == entries_0_1_entry_tag;
  wire             hitMask_1_0_2 =
    io_write_1_valid & valids_0_2 & io_write_1_bits_setIdx == entries_0_2_setIdx
    & io_write_1_bits_entry_tag == entries_0_2_entry_tag;
  wire             hitMask_1_0_3 =
    io_write_1_valid & valids_0_3 & io_write_1_bits_setIdx == entries_0_3_setIdx
    & io_write_1_bits_entry_tag == entries_0_3_entry_tag;
  wire             hitMask_1_1_0 =
    _hitMask_1_0_T_5 & _hitMask_1_0_T_6
    & io_write_1_bits_entry_tag == entries_1_0_entry_tag;
  wire             hitMask_1_1_1 =
    _hitMask_1_1_T_5 & _hitMask_1_1_T_6
    & io_write_1_bits_entry_tag == entries_1_1_entry_tag;
  wire             hitMask_1_1_2 =
    _hitMask_1_2_T_5 & _hitMask_1_2_T_6
    & io_write_1_bits_entry_tag == entries_1_2_entry_tag;
  wire             hitMask_1_1_3 =
    _hitMask_1_3_T_5 & _hitMask_1_3_T_6
    & io_write_1_bits_entry_tag == entries_1_3_entry_tag;
  wire [3:0]       _GEN_23 =
    4'({1'h0,
        3'({1'h0, 2'({1'h0, hitMask_1_0_0} + {1'h0, hitMask_1_0_1})}
           + {1'h0, 2'({1'h0, hitMask_1_0_2} + {1'h0, hitMask_1_0_3})})}
       + {1'h0,
          3'({1'h0, 2'({1'h0, hitMask_1_1_0} + {1'h0, hitMask_1_1_1})}
             + {1'h0, 2'({1'h0, hitMask_1_1_2} + {1'h0, hitMask_1_1_3})})});
  wire             _GEN_24 = io_write_1_valid & (|(_GEN_23[3:1]));
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (_GEN_0 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_2 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (writeSameEntry_probe & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_4 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
      if (_GEN_24 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire             _hitRowsVec_T_6 = hitMask_1_0_0 | hitMask_1_0_1;
  wire             hit_1 =
    _hitRowsVec_T_6 | hitMask_1_0_2 | hitMask_1_0_3 | hitMask_1_1_0 | hitMask_1_1_1
    | hitMask_1_1_2 | hitMask_1_1_3;
  wire             hitRowsVec_1_0 = _hitRowsVec_T_6 | hitMask_1_0_2 | hitMask_1_0_3;
  wire             rowIdx_1 =
    hitMask_1_1_0 | hitMask_1_1_1 | hitMask_1_1_2 | hitMask_1_1_3;
  wire [1:0]       hitRowIdxVec_1_0 =
    {|{hitMask_1_0_3, hitMask_1_0_2}, hitMask_1_0_3 | hitMask_1_0_1};
  wire [1:0]       hitRowIdxVec_1_1 =
    {|{hitMask_1_1_3, hitMask_1_1_2}, hitMask_1_1_3 | hitMask_1_1_1};
  wire [1:0]       _GEN_25 = rowIdx_1 ? hitRowIdxVec_1_1 : hitRowIdxVec_1_0;
  wire [3:0]       _GEN_26 = rowIdx_1 ? _GEN_6 : _GEN_7;
  wire             hitNotWritten_1 = hit_1 & _GEN_26[_GEN_25];
  wire             hitWritten_1 = hit_1 & ~_GEN_26[_GEN_25];
  wire             _GEN_27 = io_write_1_valid & ~hit_1;
  wire             _GEN_28 = io_write_1_valid & hitNotWritten_1;
  wire             _GEN_29 = io_write_1_valid & hitWritten_1;
  wire             _GEN_30 = io_write_1_valid & hit_1;
  reg  [2:0]       state_reg;
  wire             emptyVec_0 =
    ~(readValidVec_0_0 | readValidVec_0_1 | readValidVec_0_2 | readValidVec_0_3);
  wire             fullVec_0 =
    readValidVec_0_0 & readValidVec_0_1 & readValidVec_0_2 & readValidVec_0_3;
  wire [1:0]       readIdx =
    readValidVec_0_0 ? 2'h0 : readValidVec_0_1 ? 2'h1 : {1'h1, ~readValidVec_0_2};
  wire [1:0]       replacerWay_0 =
    {state_reg[2], state_reg[2] ? state_reg[1] : state_reg[0]};
  wire             _GEN_31 = io_write_0_valid & fullVec_0;
  wire [2:0]       _GEN_32 =
    3'({1'h0, 2'({1'h0, readValidVec_0_0} + {1'h0, readValidVec_0_1})}
       + {1'h0, 2'({1'h0, readValidVec_0_2} + {1'h0, readValidVec_0_3})});
  reg  [2:0]       state_reg_1;
  wire             emptyVec_1 =
    ~(readValidVec_1_0 | readValidVec_1_1 | readValidVec_1_2 | readValidVec_1_3);
  wire             fullVec_1 =
    readValidVec_1_0 & readValidVec_1_1 & readValidVec_1_2 & readValidVec_1_3;
  wire [1:0]       readIdx_1 =
    readValidVec_1_0 ? 2'h0 : readValidVec_1_1 ? 2'h1 : {1'h1, ~readValidVec_1_2};
  wire [1:0]       replacerWay_1 =
    {state_reg_1[2], state_reg_1[2] ? state_reg_1[1] : state_reg_1[0]};
  wire             _GEN_33 = io_write_1_valid & fullVec_1;
  wire [2:0]       _GEN_34 =
    3'({1'h0, 2'({1'h0, readValidVec_1_0} + {1'h0, readValidVec_1_1})}
       + {1'h0, 2'({1'h0, readValidVec_1_2} + {1'h0, readValidVec_1_3})});
  wire [1:0]       victim =
    setIdxHitVec_0 | setIdxHitVec_1 | setIdxHitVec_2 | setIdxHitVec_3
      ? {|{setIdxHitVec_3, setIdxHitVec_2}, setIdxHitVec_3 | setIdxHitVec_1}
      : needWrite_0_0 & needWrite_0_1 & needWrite_0_2 & needWrite_0_3
          ? replacerWay_0
          : needWrite_0_0 ? (needWrite_0_1 ? {1'h1, needWrite_0_2} : 2'h1) : 2'h0;
  wire             _GEN_35 = ~hit & victim == 2'h0;
  wire             _GEN_36 = ~hit & victim == 2'h1;
  wire             _GEN_37 = ~hit & victim == 2'h2;
  wire             _GEN_38 = ~hit & (&victim);
  wire             _GEN_39 = _GEN_5 == 2'h0;
  wire             _GEN_40 = _GEN_39 | _GEN_35;
  wire             _GEN_41 = ~rowIdx & _GEN_39;
  wire             _GEN_42 = _GEN_5 == 2'h1;
  wire             _GEN_43 = _GEN_42 | _GEN_36;
  wire             _GEN_44 = ~rowIdx & _GEN_42;
  wire             _GEN_45 = _GEN_5 == 2'h2;
  wire             _GEN_46 = _GEN_45 | _GEN_37;
  wire             _GEN_47 = ~rowIdx & _GEN_45;
  wire             _GEN_48 = (&_GEN_5) | _GEN_38;
  wire             _GEN_49 = ~rowIdx & (&_GEN_5);
  wire             _GEN_50 = rowIdx & _GEN_39;
  wire             _GEN_51 = rowIdx & _GEN_42;
  wire             _GEN_52 = rowIdx & _GEN_45;
  wire             _GEN_53 = rowIdx & (&_GEN_5);
  wire [3:0][2:0]  _GEN_54 = rowIdx ? _GEN_16 : _GEN_17;
  wire [3:0][1:0]  _GEN_55 = rowIdx ? _GEN_18 : _GEN_19;
  wire [3:0][12:0] _GEN_56 = rowIdx ? _GEN_14 : _GEN_15;
  wire [3:0]       _GEN_57 = rowIdx ? _GEN_12 : _GEN_13;
  wire [3:0][8:0]  _GEN_58 = rowIdx ? _GEN_10 : _GEN_11;
  wire             _GEN_59 =
    {_GEN_58[_GEN_5],
     _GEN_57[_GEN_5],
     _GEN_56[_GEN_5],
     _GEN_54[_GEN_5],
     _GEN_55[_GEN_5]} == {io_write_0_bits_setIdx,
                          io_write_0_bits_entry_valid,
                          io_write_0_bits_entry_tag,
                          io_write_0_bits_entry_takenCtr_value,
                          io_write_0_bits_usefulCtr_value};
  wire             _GEN_60 = ~hit | hitNotWritten | ~hitWritten | _GEN_59 | rowIdx;
  wire             _GEN_61 =
    hit
      ? (hitNotWritten ? _GEN_41 | _GEN_35 : hitWritten & ~_GEN_59 & _GEN_41 | _GEN_35)
      : _GEN_35;
  wire             _GEN_62 =
    hit
      ? (hitNotWritten ? _GEN_44 | _GEN_36 : hitWritten & ~_GEN_59 & _GEN_44 | _GEN_36)
      : _GEN_36;
  wire             _GEN_63 =
    hit
      ? (hitNotWritten ? _GEN_47 | _GEN_37 : hitWritten & ~_GEN_59 & _GEN_47 | _GEN_37)
      : _GEN_37;
  wire             _GEN_64 =
    hit
      ? (hitNotWritten ? _GEN_49 | _GEN_38 : hitWritten & ~_GEN_59 & _GEN_49 | _GEN_38)
      : _GEN_38;
  wire             _GEN_65 = ~hitWritten | _GEN_59 | ~_GEN_50;
  wire             _GEN_66 = ~hitWritten | _GEN_59 | ~_GEN_51;
  wire             _GEN_67 = ~hitWritten | _GEN_59 | ~_GEN_52;
  wire             _GEN_68 = ~hitWritten | _GEN_59 | ~_GEN_53;
  wire             _GEN_69 = ~hit | ~hitNotWritten & (~hitWritten | _GEN_59) | rowIdx;
  wire             _updateCnt_T_8 =
    (&_GEN_54[_GEN_5]) & io_takenMask_0 | _GEN_54[_GEN_5] == 3'h0 & ~io_takenMask_0;
  wire [2:0]       _updateCnt_T_13 =
    io_takenMask_0 ? 3'(_GEN_54[_GEN_5] + 3'h1) : 3'(_GEN_54[_GEN_5] - 3'h1);
  wire             _GEN_70 = hit & ~rowIdx & _GEN_39;
  wire             _GEN_71 = io_write_0_valid & (_GEN_70 | _GEN_61);
  wire             _GEN_72 = hit & ~rowIdx & _GEN_42;
  wire             _GEN_73 = io_write_0_valid & (_GEN_72 | _GEN_62);
  wire             _GEN_74 = hit & ~rowIdx & _GEN_45;
  wire             _GEN_75 = io_write_0_valid & (_GEN_74 | _GEN_63);
  wire             _GEN_76 = hit & ~rowIdx & (&_GEN_5);
  wire             _GEN_77 = io_write_0_valid & (_GEN_76 | _GEN_64);
  wire             _GEN_78 = hit & _GEN_50;
  wire             _GEN_79 = hit & _GEN_51;
  wire             _GEN_80 = hit & _GEN_52;
  wire             _GEN_81 = hit & _GEN_53;
  wire             _GEN_82 =
    _GEN_70 | (_GEN_69 ? _GEN_35 | valids_0_0 : _GEN_40 | valids_0_0);
  wire             _GEN_83 =
    _GEN_72 | (_GEN_69 ? _GEN_36 | valids_0_1 : _GEN_43 | valids_0_1);
  wire             _GEN_84 =
    _GEN_74 | (_GEN_69 ? _GEN_37 | valids_0_2 : _GEN_46 | valids_0_2);
  wire             _GEN_85 =
    _GEN_76 | (_GEN_69 ? _GEN_38 | valids_0_3 : _GEN_48 | valids_0_3);
  wire             _GEN_86 =
    _GEN_78
    | (hit
         ? (hitNotWritten
              ? _GEN_50 | valids_1_0
              : hitWritten & ~_GEN_59 & _GEN_50 | valids_1_0)
         : valids_1_0);
  wire             _GEN_87 =
    _GEN_79
    | (hit
         ? (hitNotWritten
              ? _GEN_51 | valids_1_1
              : hitWritten & ~_GEN_59 & _GEN_51 | valids_1_1)
         : valids_1_1);
  wire             _GEN_88 =
    _GEN_80
    | (hit
         ? (hitNotWritten
              ? _GEN_52 | valids_1_2
              : hitWritten & ~_GEN_59 & _GEN_52 | valids_1_2)
         : valids_1_2);
  wire             _GEN_89 =
    _GEN_81
    | (hit
         ? (hitNotWritten
              ? _GEN_53 | valids_1_3
              : hitWritten & ~_GEN_59 & _GEN_53 | valids_1_3)
         : valids_1_3);
  wire             _GEN_90 =
    io_write_0_valid & (_GEN_78 | hit & ~hitNotWritten & hitWritten & ~_GEN_59 & _GEN_50)
    | needWrite_1_0;
  wire             _GEN_91 =
    io_write_0_valid & (_GEN_79 | hit & ~hitNotWritten & hitWritten & ~_GEN_59 & _GEN_51)
    | needWrite_1_1;
  wire             _GEN_92 =
    io_write_0_valid & (_GEN_80 | hit & ~hitNotWritten & hitWritten & ~_GEN_59 & _GEN_52)
    | needWrite_1_2;
  wire             _GEN_93 =
    io_write_0_valid & (_GEN_81 | hit & ~hitNotWritten & hitWritten & ~_GEN_59 & _GEN_53)
    | needWrite_1_3;
  wire [1:0]       victim_1 =
    setIdxHitVec_0_1 | setIdxHitVec_1_1 | setIdxHitVec_2_1 | setIdxHitVec_3_1
      ? {|{setIdxHitVec_3_1, setIdxHitVec_2_1}, setIdxHitVec_3_1 | setIdxHitVec_1_1}
      : needWrite_1_0 & needWrite_1_1 & needWrite_1_2 & needWrite_1_3
          ? replacerWay_1
          : needWrite_1_0 ? (needWrite_1_1 ? {1'h1, needWrite_1_2} : 2'h1) : 2'h0;
  wire             _GEN_94 = ~hit_1 & victim_1 == 2'h0;
  wire             _GEN_95 = ~hit_1 & victim_1 == 2'h1;
  wire             _GEN_96 = ~hit_1 & victim_1 == 2'h2;
  wire             _GEN_97 = ~hit_1 & (&victim_1);
  wire             _GEN_98 = _GEN_25 == 2'h0;
  wire             _GEN_99 = ~rowIdx_1 & _GEN_98;
  wire             _GEN_100 = _GEN_25 == 2'h1;
  wire             _GEN_101 = ~rowIdx_1 & _GEN_100;
  wire             _GEN_102 = _GEN_25 == 2'h2;
  wire             _GEN_103 = ~rowIdx_1 & _GEN_102;
  wire             _GEN_104 = ~rowIdx_1 & (&_GEN_25);
  wire             _GEN_105 = _GEN_98 | _GEN_94;
  wire             _GEN_106 = rowIdx_1 & _GEN_98;
  wire             _GEN_107 = _GEN_100 | _GEN_95;
  wire             _GEN_108 = rowIdx_1 & _GEN_100;
  wire             _GEN_109 = _GEN_102 | _GEN_96;
  wire             _GEN_110 = rowIdx_1 & _GEN_102;
  wire             _GEN_111 = (&_GEN_25) | _GEN_97;
  wire             _GEN_112 = rowIdx_1 & (&_GEN_25);
  wire [3:0][2:0]  _GEN_113 = rowIdx_1 ? _GEN_16 : _GEN_17;
  wire [3:0][1:0]  _GEN_114 = rowIdx_1 ? _GEN_18 : _GEN_19;
  wire [3:0][12:0] _GEN_115 = rowIdx_1 ? _GEN_14 : _GEN_15;
  wire [3:0]       _GEN_116 = rowIdx_1 ? _GEN_12 : _GEN_13;
  wire [3:0][8:0]  _GEN_117 = rowIdx_1 ? _GEN_10 : _GEN_11;
  wire             _GEN_118 =
    {_GEN_117[_GEN_25],
     _GEN_116[_GEN_25],
     _GEN_115[_GEN_25],
     _GEN_113[_GEN_25],
     _GEN_114[_GEN_25]} == {io_write_1_bits_setIdx,
                            io_write_1_bits_entry_valid,
                            io_write_1_bits_entry_tag,
                            io_write_1_bits_entry_takenCtr_value,
                            io_write_1_bits_usefulCtr_value};
  wire             _GEN_119 =
    ~hit_1 | hitNotWritten_1 | ~hitWritten_1 | _GEN_118 | ~rowIdx_1;
  wire             _GEN_120 =
    hit_1
      ? (hitNotWritten_1
           ? _GEN_106 | _GEN_94
           : hitWritten_1 & ~_GEN_118 & _GEN_106 | _GEN_94)
      : _GEN_94;
  wire             _GEN_121 =
    hit_1
      ? (hitNotWritten_1
           ? _GEN_108 | _GEN_95
           : hitWritten_1 & ~_GEN_118 & _GEN_108 | _GEN_95)
      : _GEN_95;
  wire             _GEN_122 =
    hit_1
      ? (hitNotWritten_1
           ? _GEN_110 | _GEN_96
           : hitWritten_1 & ~_GEN_118 & _GEN_110 | _GEN_96)
      : _GEN_96;
  wire             _GEN_123 =
    hit_1
      ? (hitNotWritten_1
           ? _GEN_112 | _GEN_97
           : hitWritten_1 & ~_GEN_118 & _GEN_112 | _GEN_97)
      : _GEN_97;
  wire             _GEN_124 = hit_1 & _GEN_99;
  wire             _GEN_125 = hit_1 & _GEN_101;
  wire             _GEN_126 = hit_1 & _GEN_103;
  wire             _GEN_127 = hit_1 & _GEN_104;
  wire             _GEN_128 = hit_1 & rowIdx_1 & _GEN_98;
  wire             _GEN_129 = hit_1 & rowIdx_1 & _GEN_100;
  wire             _GEN_130 = hit_1 & rowIdx_1 & _GEN_102;
  wire             _GEN_131 = hit_1 & rowIdx_1 & (&_GEN_25);
  wire             _GEN_132 = io_read_0_ready & ~emptyVec_0;
  wire             _GEN_133 = io_read_1_ready & ~emptyVec_1;
  wire             _GEN_134 = io_write_0_valid ? _GEN_82 : valids_0_0;
  wire             _GEN_135 = io_write_0_valid ? _GEN_83 : valids_0_1;
  wire             _GEN_136 = io_write_0_valid ? _GEN_84 : valids_0_2;
  wire             _GEN_137 = io_write_0_valid ? _GEN_85 : valids_0_3;
  wire             _GEN_138 = io_write_0_valid ? _GEN_86 : valids_1_0;
  wire             _GEN_139 = io_write_0_valid ? _GEN_87 : valids_1_1;
  wire             _GEN_140 = io_write_0_valid ? _GEN_88 : valids_1_2;
  wire             _GEN_141 = io_write_0_valid ? _GEN_89 : valids_1_3;
  wire             _GEN_142 = _GEN_94 | _GEN_138;
  wire             _GEN_143 = _GEN_95 | _GEN_139;
  wire             _GEN_144 = _GEN_96 | _GEN_140;
  wire             _GEN_145 = _GEN_97 | _GEN_141;
  wire             _GEN_146 = _GEN_105 | _GEN_138;
  wire             _GEN_147 = _GEN_107 | _GEN_139;
  wire             _GEN_148 = _GEN_109 | _GEN_140;
  wire             _GEN_149 = _GEN_111 | _GEN_141;
  wire             _GEN_150 = ~hitWritten_1 | _GEN_118 | ~rowIdx_1;
  wire             _updateCnt_T_23 =
    (&_GEN_113[_GEN_25]) & io_takenMask_1 | _GEN_113[_GEN_25] == 3'h0 & ~io_takenMask_1;
  wire [2:0]       _updateCnt_T_28 =
    io_takenMask_1 ? 3'(_GEN_113[_GEN_25] + 3'h1) : 3'(_GEN_113[_GEN_25] - 3'h1);
  wire [1:0]       writeTouchVec_0_bits = _GEN_9 ? victim : 2'h0;
  wire [1:0]       writeTouchVec_1_bits = _GEN_27 ? victim_1 : 2'h0;
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      needWrite_0_0 <= 1'h0;
      needWrite_0_1 <= 1'h0;
      needWrite_0_2 <= 1'h0;
      needWrite_0_3 <= 1'h0;
      needWrite_1_0 <= 1'h0;
      needWrite_1_1 <= 1'h0;
      needWrite_1_2 <= 1'h0;
      needWrite_1_3 <= 1'h0;
      entries_0_0_setIdx <= 9'h0;
      entries_0_0_entry_valid <= 1'h0;
      entries_0_0_entry_tag <= 13'h0;
      entries_0_0_entry_takenCtr_value <= 3'h0;
      entries_0_0_usefulCtr_value <= 2'h0;
      entries_0_1_setIdx <= 9'h0;
      entries_0_1_entry_valid <= 1'h0;
      entries_0_1_entry_tag <= 13'h0;
      entries_0_1_entry_takenCtr_value <= 3'h0;
      entries_0_1_usefulCtr_value <= 2'h0;
      entries_0_2_setIdx <= 9'h0;
      entries_0_2_entry_valid <= 1'h0;
      entries_0_2_entry_tag <= 13'h0;
      entries_0_2_entry_takenCtr_value <= 3'h0;
      entries_0_2_usefulCtr_value <= 2'h0;
      entries_0_3_setIdx <= 9'h0;
      entries_0_3_entry_valid <= 1'h0;
      entries_0_3_entry_tag <= 13'h0;
      entries_0_3_entry_takenCtr_value <= 3'h0;
      entries_0_3_usefulCtr_value <= 2'h0;
      entries_1_0_setIdx <= 9'h0;
      entries_1_0_entry_valid <= 1'h0;
      entries_1_0_entry_tag <= 13'h0;
      entries_1_0_entry_takenCtr_value <= 3'h0;
      entries_1_0_usefulCtr_value <= 2'h0;
      entries_1_1_setIdx <= 9'h0;
      entries_1_1_entry_valid <= 1'h0;
      entries_1_1_entry_tag <= 13'h0;
      entries_1_1_entry_takenCtr_value <= 3'h0;
      entries_1_1_usefulCtr_value <= 2'h0;
      entries_1_2_setIdx <= 9'h0;
      entries_1_2_entry_valid <= 1'h0;
      entries_1_2_entry_tag <= 13'h0;
      entries_1_2_entry_takenCtr_value <= 3'h0;
      entries_1_2_usefulCtr_value <= 2'h0;
      entries_1_3_setIdx <= 9'h0;
      entries_1_3_entry_valid <= 1'h0;
      entries_1_3_entry_tag <= 13'h0;
      entries_1_3_entry_takenCtr_value <= 3'h0;
      entries_1_3_usefulCtr_value <= 2'h0;
      valids_0_0 <= 1'h0;
      valids_0_1 <= 1'h0;
      valids_0_2 <= 1'h0;
      valids_0_3 <= 1'h0;
      valids_1_0 <= 1'h0;
      valids_1_1 <= 1'h0;
      valids_1_2 <= 1'h0;
      valids_1_3 <= 1'h0;
      state_reg <= 3'h0;
      state_reg_1 <= 3'h0;
    end
    else begin
      needWrite_0_0 <=
        ~(_GEN_132 & readIdx == 2'h0)
        & (io_write_1_valid
           & (_GEN_124 | hit_1 & ~hitNotWritten_1 & hitWritten_1 & ~_GEN_118 & _GEN_99)
           | (io_write_0_valid
                ? _GEN_70 | (_GEN_60 ? _GEN_35 | needWrite_0_0 : _GEN_40 | needWrite_0_0)
                : needWrite_0_0));
      needWrite_0_1 <=
        ~(_GEN_132 & readIdx == 2'h1)
        & (io_write_1_valid
           & (_GEN_125 | hit_1 & ~hitNotWritten_1 & hitWritten_1 & ~_GEN_118 & _GEN_101)
           | (io_write_0_valid
                ? _GEN_72 | (_GEN_60 ? _GEN_36 | needWrite_0_1 : _GEN_43 | needWrite_0_1)
                : needWrite_0_1));
      needWrite_0_2 <=
        ~(_GEN_132 & readIdx == 2'h2)
        & (io_write_1_valid
           & (_GEN_126 | hit_1 & ~hitNotWritten_1 & hitWritten_1 & ~_GEN_118 & _GEN_103)
           | (io_write_0_valid
                ? _GEN_74 | (_GEN_60 ? _GEN_37 | needWrite_0_2 : _GEN_46 | needWrite_0_2)
                : needWrite_0_2));
      needWrite_0_3 <=
        ~(_GEN_132 & (&readIdx))
        & (io_write_1_valid
           & (_GEN_127 | hit_1 & ~hitNotWritten_1 & hitWritten_1 & ~_GEN_118 & _GEN_104)
           | (io_write_0_valid
                ? _GEN_76 | (_GEN_60 ? _GEN_38 | needWrite_0_3 : _GEN_48 | needWrite_0_3)
                : needWrite_0_3));
      needWrite_1_0 <=
        ~(_GEN_133 & readIdx_1 == 2'h0)
        & (io_write_1_valid
             ? _GEN_128 | (_GEN_119 ? _GEN_94 | _GEN_90 : _GEN_105 | _GEN_90)
             : _GEN_90);
      needWrite_1_1 <=
        ~(_GEN_133 & readIdx_1 == 2'h1)
        & (io_write_1_valid
             ? _GEN_129 | (_GEN_119 ? _GEN_95 | _GEN_91 : _GEN_107 | _GEN_91)
             : _GEN_91);
      needWrite_1_2 <=
        ~(_GEN_133 & readIdx_1 == 2'h2)
        & (io_write_1_valid
             ? _GEN_130 | (_GEN_119 ? _GEN_96 | _GEN_92 : _GEN_109 | _GEN_92)
             : _GEN_92);
      needWrite_1_3 <=
        ~(_GEN_133 & (&readIdx_1))
        & (io_write_1_valid
             ? _GEN_131 | (_GEN_119 ? _GEN_97 | _GEN_93 : _GEN_111 | _GEN_93)
             : _GEN_93);
      if (io_write_1_valid) begin
        if (_GEN_124) begin
          entries_0_0_setIdx <= io_write_1_bits_setIdx;
          entries_0_0_entry_valid <= io_write_1_bits_entry_valid;
          entries_0_0_entry_tag <= io_write_1_bits_entry_tag;
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_0_0_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_0_0_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_0_0_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
          entries_0_0_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
        end
        else if (hit_1) begin
          if (hitNotWritten_1) begin
            if (_GEN_99) begin
              entries_0_0_setIdx <= io_write_1_bits_setIdx;
              entries_0_0_entry_valid <= io_write_1_bits_entry_valid;
              entries_0_0_entry_tag <= io_write_1_bits_entry_tag;
              entries_0_0_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
              entries_0_0_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
            end
            else begin
              if (_GEN_71) begin
                entries_0_0_setIdx <= io_write_0_bits_setIdx;
                entries_0_0_entry_valid <= io_write_0_bits_entry_valid;
                entries_0_0_entry_tag <= io_write_0_bits_entry_tag;
              end
              if (io_write_0_valid) begin
                if (_GEN_70) begin
                  if (hit) begin
                    if (_updateCnt_T_8)
                      entries_0_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
                    else
                      entries_0_0_entry_takenCtr_value <= _updateCnt_T_13;
                  end
                  else
                    entries_0_0_entry_takenCtr_value <=
                      io_write_0_bits_entry_takenCtr_value;
                end
                else if (_GEN_61)
                  entries_0_0_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              if (_GEN_71)
                entries_0_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (~hitWritten_1 | _GEN_118 | ~_GEN_99) begin
            if (_GEN_71) begin
              entries_0_0_setIdx <= io_write_0_bits_setIdx;
              entries_0_0_entry_valid <= io_write_0_bits_entry_valid;
              entries_0_0_entry_tag <= io_write_0_bits_entry_tag;
            end
            if (io_write_0_valid) begin
              if (_GEN_70) begin
                if (hit) begin
                  if (_updateCnt_T_8)
                    entries_0_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
                  else
                    entries_0_0_entry_takenCtr_value <= _updateCnt_T_13;
                end
                else
                  entries_0_0_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              else if (_GEN_61)
                entries_0_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            if (_GEN_71)
              entries_0_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
          else begin
            entries_0_0_setIdx <= io_write_1_bits_setIdx;
            entries_0_0_entry_valid <= io_write_1_bits_entry_valid;
            entries_0_0_entry_tag <= io_write_1_bits_entry_tag;
            entries_0_0_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
            entries_0_0_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
          end
        end
        else begin
          if (_GEN_71) begin
            entries_0_0_setIdx <= io_write_0_bits_setIdx;
            entries_0_0_entry_valid <= io_write_0_bits_entry_valid;
            entries_0_0_entry_tag <= io_write_0_bits_entry_tag;
          end
          if (io_write_0_valid) begin
            if (_GEN_70) begin
              if (hit) begin
                if (_updateCnt_T_8)
                  entries_0_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
                else
                  entries_0_0_entry_takenCtr_value <= _updateCnt_T_13;
              end
              else
                entries_0_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_61)
              entries_0_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_71)
            entries_0_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_125) begin
          entries_0_1_setIdx <= io_write_1_bits_setIdx;
          entries_0_1_entry_valid <= io_write_1_bits_entry_valid;
          entries_0_1_entry_tag <= io_write_1_bits_entry_tag;
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_0_1_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_0_1_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_0_1_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
          entries_0_1_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
        end
        else if (hit_1) begin
          if (hitNotWritten_1) begin
            if (_GEN_101) begin
              entries_0_1_setIdx <= io_write_1_bits_setIdx;
              entries_0_1_entry_valid <= io_write_1_bits_entry_valid;
              entries_0_1_entry_tag <= io_write_1_bits_entry_tag;
              entries_0_1_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
              entries_0_1_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
            end
            else begin
              if (_GEN_73) begin
                entries_0_1_setIdx <= io_write_0_bits_setIdx;
                entries_0_1_entry_valid <= io_write_0_bits_entry_valid;
                entries_0_1_entry_tag <= io_write_0_bits_entry_tag;
              end
              if (io_write_0_valid) begin
                if (_GEN_72) begin
                  if (hit) begin
                    if (_updateCnt_T_8)
                      entries_0_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
                    else
                      entries_0_1_entry_takenCtr_value <= _updateCnt_T_13;
                  end
                  else
                    entries_0_1_entry_takenCtr_value <=
                      io_write_0_bits_entry_takenCtr_value;
                end
                else if (_GEN_62)
                  entries_0_1_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              if (_GEN_73)
                entries_0_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (~hitWritten_1 | _GEN_118 | ~_GEN_101) begin
            if (_GEN_73) begin
              entries_0_1_setIdx <= io_write_0_bits_setIdx;
              entries_0_1_entry_valid <= io_write_0_bits_entry_valid;
              entries_0_1_entry_tag <= io_write_0_bits_entry_tag;
            end
            if (io_write_0_valid) begin
              if (_GEN_72) begin
                if (hit) begin
                  if (_updateCnt_T_8)
                    entries_0_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
                  else
                    entries_0_1_entry_takenCtr_value <= _updateCnt_T_13;
                end
                else
                  entries_0_1_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              else if (_GEN_62)
                entries_0_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            if (_GEN_73)
              entries_0_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
          else begin
            entries_0_1_setIdx <= io_write_1_bits_setIdx;
            entries_0_1_entry_valid <= io_write_1_bits_entry_valid;
            entries_0_1_entry_tag <= io_write_1_bits_entry_tag;
            entries_0_1_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
            entries_0_1_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
          end
        end
        else begin
          if (_GEN_73) begin
            entries_0_1_setIdx <= io_write_0_bits_setIdx;
            entries_0_1_entry_valid <= io_write_0_bits_entry_valid;
            entries_0_1_entry_tag <= io_write_0_bits_entry_tag;
          end
          if (io_write_0_valid) begin
            if (_GEN_72) begin
              if (hit) begin
                if (_updateCnt_T_8)
                  entries_0_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
                else
                  entries_0_1_entry_takenCtr_value <= _updateCnt_T_13;
              end
              else
                entries_0_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_62)
              entries_0_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_73)
            entries_0_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_126) begin
          entries_0_2_setIdx <= io_write_1_bits_setIdx;
          entries_0_2_entry_valid <= io_write_1_bits_entry_valid;
          entries_0_2_entry_tag <= io_write_1_bits_entry_tag;
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_0_2_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_0_2_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_0_2_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
          entries_0_2_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
        end
        else if (hit_1) begin
          if (hitNotWritten_1) begin
            if (_GEN_103) begin
              entries_0_2_setIdx <= io_write_1_bits_setIdx;
              entries_0_2_entry_valid <= io_write_1_bits_entry_valid;
              entries_0_2_entry_tag <= io_write_1_bits_entry_tag;
              entries_0_2_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
              entries_0_2_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
            end
            else begin
              if (_GEN_75) begin
                entries_0_2_setIdx <= io_write_0_bits_setIdx;
                entries_0_2_entry_valid <= io_write_0_bits_entry_valid;
                entries_0_2_entry_tag <= io_write_0_bits_entry_tag;
              end
              if (io_write_0_valid) begin
                if (_GEN_74) begin
                  if (hit) begin
                    if (_updateCnt_T_8)
                      entries_0_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
                    else
                      entries_0_2_entry_takenCtr_value <= _updateCnt_T_13;
                  end
                  else
                    entries_0_2_entry_takenCtr_value <=
                      io_write_0_bits_entry_takenCtr_value;
                end
                else if (_GEN_63)
                  entries_0_2_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              if (_GEN_75)
                entries_0_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (~hitWritten_1 | _GEN_118 | ~_GEN_103) begin
            if (_GEN_75) begin
              entries_0_2_setIdx <= io_write_0_bits_setIdx;
              entries_0_2_entry_valid <= io_write_0_bits_entry_valid;
              entries_0_2_entry_tag <= io_write_0_bits_entry_tag;
            end
            if (io_write_0_valid) begin
              if (_GEN_74) begin
                if (hit) begin
                  if (_updateCnt_T_8)
                    entries_0_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
                  else
                    entries_0_2_entry_takenCtr_value <= _updateCnt_T_13;
                end
                else
                  entries_0_2_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              else if (_GEN_63)
                entries_0_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            if (_GEN_75)
              entries_0_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
          else begin
            entries_0_2_setIdx <= io_write_1_bits_setIdx;
            entries_0_2_entry_valid <= io_write_1_bits_entry_valid;
            entries_0_2_entry_tag <= io_write_1_bits_entry_tag;
            entries_0_2_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
            entries_0_2_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
          end
        end
        else begin
          if (_GEN_75) begin
            entries_0_2_setIdx <= io_write_0_bits_setIdx;
            entries_0_2_entry_valid <= io_write_0_bits_entry_valid;
            entries_0_2_entry_tag <= io_write_0_bits_entry_tag;
          end
          if (io_write_0_valid) begin
            if (_GEN_74) begin
              if (hit) begin
                if (_updateCnt_T_8)
                  entries_0_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
                else
                  entries_0_2_entry_takenCtr_value <= _updateCnt_T_13;
              end
              else
                entries_0_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_63)
              entries_0_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_75)
            entries_0_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_127) begin
          entries_0_3_setIdx <= io_write_1_bits_setIdx;
          entries_0_3_entry_valid <= io_write_1_bits_entry_valid;
          entries_0_3_entry_tag <= io_write_1_bits_entry_tag;
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_0_3_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_0_3_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_0_3_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
          entries_0_3_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
        end
        else if (hit_1) begin
          if (hitNotWritten_1) begin
            if (_GEN_104) begin
              entries_0_3_setIdx <= io_write_1_bits_setIdx;
              entries_0_3_entry_valid <= io_write_1_bits_entry_valid;
              entries_0_3_entry_tag <= io_write_1_bits_entry_tag;
              entries_0_3_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
              entries_0_3_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
            end
            else begin
              if (_GEN_77) begin
                entries_0_3_setIdx <= io_write_0_bits_setIdx;
                entries_0_3_entry_valid <= io_write_0_bits_entry_valid;
                entries_0_3_entry_tag <= io_write_0_bits_entry_tag;
              end
              if (io_write_0_valid) begin
                if (_GEN_76) begin
                  if (hit) begin
                    if (_updateCnt_T_8)
                      entries_0_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
                    else
                      entries_0_3_entry_takenCtr_value <= _updateCnt_T_13;
                  end
                  else
                    entries_0_3_entry_takenCtr_value <=
                      io_write_0_bits_entry_takenCtr_value;
                end
                else if (_GEN_64)
                  entries_0_3_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              if (_GEN_77)
                entries_0_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (~hitWritten_1 | _GEN_118 | ~_GEN_104) begin
            if (_GEN_77) begin
              entries_0_3_setIdx <= io_write_0_bits_setIdx;
              entries_0_3_entry_valid <= io_write_0_bits_entry_valid;
              entries_0_3_entry_tag <= io_write_0_bits_entry_tag;
            end
            if (io_write_0_valid) begin
              if (_GEN_76) begin
                if (hit) begin
                  if (_updateCnt_T_8)
                    entries_0_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
                  else
                    entries_0_3_entry_takenCtr_value <= _updateCnt_T_13;
                end
                else
                  entries_0_3_entry_takenCtr_value <=
                    io_write_0_bits_entry_takenCtr_value;
              end
              else if (_GEN_64)
                entries_0_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            if (_GEN_77)
              entries_0_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
          else begin
            entries_0_3_setIdx <= io_write_1_bits_setIdx;
            entries_0_3_entry_valid <= io_write_1_bits_entry_valid;
            entries_0_3_entry_tag <= io_write_1_bits_entry_tag;
            entries_0_3_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
            entries_0_3_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
          end
        end
        else begin
          if (_GEN_77) begin
            entries_0_3_setIdx <= io_write_0_bits_setIdx;
            entries_0_3_entry_valid <= io_write_0_bits_entry_valid;
            entries_0_3_entry_tag <= io_write_0_bits_entry_tag;
          end
          if (io_write_0_valid) begin
            if (_GEN_76) begin
              if (hit) begin
                if (_updateCnt_T_8)
                  entries_0_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
                else
                  entries_0_3_entry_takenCtr_value <= _updateCnt_T_13;
              end
              else
                entries_0_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_64)
              entries_0_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_77)
            entries_0_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_128) begin
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_1_0_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_1_0_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_1_0_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        end
        else if (_GEN_120)
          entries_1_0_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        else if (io_write_0_valid) begin
          if (_GEN_78) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_0_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_50)
                entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_65) begin
            end
            else
              entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
        end
        if (_GEN_129) begin
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_1_1_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_1_1_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_1_1_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        end
        else if (_GEN_121)
          entries_1_1_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        else if (io_write_0_valid) begin
          if (_GEN_79) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_1_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_51)
                entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_66) begin
            end
            else
              entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
        end
        if (_GEN_130) begin
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_1_2_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_1_2_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_1_2_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        end
        else if (_GEN_122)
          entries_1_2_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        else if (io_write_0_valid) begin
          if (_GEN_80) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_2_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_52)
                entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_67) begin
            end
            else
              entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
        end
        if (_GEN_131) begin
          if (hit_1) begin
            if (_updateCnt_T_23)
              entries_1_3_entry_takenCtr_value <= _GEN_113[_GEN_25];
            else
              entries_1_3_entry_takenCtr_value <= _updateCnt_T_28;
          end
          else
            entries_1_3_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        end
        else if (_GEN_123)
          entries_1_3_entry_takenCtr_value <= io_write_1_bits_entry_takenCtr_value;
        else if (io_write_0_valid) begin
          if (_GEN_81) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_3_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_53)
                entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_68) begin
            end
            else
              entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
        end
        valids_0_0 <=
          _GEN_124
          | (hit_1
               ? (hitNotWritten_1
                    ? _GEN_99 | _GEN_134
                    : hitWritten_1 & ~_GEN_118 & _GEN_99 | _GEN_134)
               : _GEN_134);
        valids_0_1 <=
          _GEN_125
          | (hit_1
               ? (hitNotWritten_1
                    ? _GEN_101 | _GEN_135
                    : hitWritten_1 & ~_GEN_118 & _GEN_101 | _GEN_135)
               : _GEN_135);
        valids_0_2 <=
          _GEN_126
          | (hit_1
               ? (hitNotWritten_1
                    ? _GEN_103 | _GEN_136
                    : hitWritten_1 & ~_GEN_118 & _GEN_103 | _GEN_136)
               : _GEN_136);
        valids_0_3 <=
          _GEN_127
          | (hit_1
               ? (hitNotWritten_1
                    ? _GEN_104 | _GEN_137
                    : hitWritten_1 & ~_GEN_118 & _GEN_104 | _GEN_137)
               : _GEN_137);
        valids_1_0 <=
          _GEN_128
          | (hit_1
               ? (hitNotWritten_1
                    ? (rowIdx_1 ? _GEN_146 : _GEN_142)
                    : _GEN_150 ? _GEN_142 : _GEN_146)
               : _GEN_142);
        valids_1_1 <=
          _GEN_129
          | (hit_1
               ? (hitNotWritten_1
                    ? (rowIdx_1 ? _GEN_147 : _GEN_143)
                    : _GEN_150 ? _GEN_143 : _GEN_147)
               : _GEN_143);
        valids_1_2 <=
          _GEN_130
          | (hit_1
               ? (hitNotWritten_1
                    ? (rowIdx_1 ? _GEN_148 : _GEN_144)
                    : _GEN_150 ? _GEN_144 : _GEN_148)
               : _GEN_144);
        valids_1_3 <=
          _GEN_131
          | (hit_1
               ? (hitNotWritten_1
                    ? (rowIdx_1 ? _GEN_149 : _GEN_145)
                    : _GEN_150 ? _GEN_145 : _GEN_149)
               : _GEN_145);
      end
      else begin
        if (_GEN_71) begin
          entries_0_0_setIdx <= io_write_0_bits_setIdx;
          entries_0_0_entry_valid <= io_write_0_bits_entry_valid;
          entries_0_0_entry_tag <= io_write_0_bits_entry_tag;
        end
        if (io_write_0_valid) begin
          if (_GEN_70) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_0_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_0_0_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_0_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (_GEN_61)
            entries_0_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          if (_GEN_72) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_0_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_0_1_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_0_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (_GEN_62)
            entries_0_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          if (_GEN_74) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_0_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_0_2_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_0_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (_GEN_63)
            entries_0_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          if (_GEN_76) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_0_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_0_3_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_0_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (_GEN_64)
            entries_0_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          if (_GEN_78) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_0_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_0_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_50)
                entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_65) begin
            end
            else
              entries_1_0_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_79) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_1_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_1_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_51)
                entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_66) begin
            end
            else
              entries_1_1_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_80) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_2_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_2_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_52)
                entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_67) begin
            end
            else
              entries_1_2_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          if (_GEN_81) begin
            if (hit) begin
              if (_updateCnt_T_8)
                entries_1_3_entry_takenCtr_value <= _GEN_54[_GEN_5];
              else
                entries_1_3_entry_takenCtr_value <= _updateCnt_T_13;
            end
            else
              entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          else if (hit) begin
            if (hitNotWritten) begin
              if (_GEN_53)
                entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
            end
            else if (_GEN_68) begin
            end
            else
              entries_1_3_entry_takenCtr_value <= io_write_0_bits_entry_takenCtr_value;
          end
          valids_0_0 <= _GEN_82;
          valids_0_1 <= _GEN_83;
          valids_0_2 <= _GEN_84;
          valids_0_3 <= _GEN_85;
          valids_1_0 <= _GEN_86;
          valids_1_1 <= _GEN_87;
          valids_1_2 <= _GEN_88;
          valids_1_3 <= _GEN_89;
        end
        if (_GEN_71)
          entries_0_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        if (_GEN_73) begin
          entries_0_1_setIdx <= io_write_0_bits_setIdx;
          entries_0_1_entry_valid <= io_write_0_bits_entry_valid;
          entries_0_1_entry_tag <= io_write_0_bits_entry_tag;
          entries_0_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_75) begin
          entries_0_2_setIdx <= io_write_0_bits_setIdx;
          entries_0_2_entry_valid <= io_write_0_bits_entry_valid;
          entries_0_2_entry_tag <= io_write_0_bits_entry_tag;
          entries_0_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        if (_GEN_77) begin
          entries_0_3_setIdx <= io_write_0_bits_setIdx;
          entries_0_3_entry_valid <= io_write_0_bits_entry_valid;
          entries_0_3_entry_tag <= io_write_0_bits_entry_tag;
          entries_0_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
      end
      if (io_write_1_valid & (_GEN_128 | _GEN_120)) begin
        entries_1_0_setIdx <= io_write_1_bits_setIdx;
        entries_1_0_entry_valid <= io_write_1_bits_entry_valid;
        entries_1_0_entry_tag <= io_write_1_bits_entry_tag;
        entries_1_0_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
      end
      else if (io_write_0_valid) begin
        if (_GEN_78) begin
          entries_1_0_setIdx <= io_write_0_bits_setIdx;
          entries_1_0_entry_valid <= io_write_0_bits_entry_valid;
          entries_1_0_entry_tag <= io_write_0_bits_entry_tag;
          entries_1_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        else if (hit) begin
          if (hitNotWritten) begin
            if (_GEN_50) begin
              entries_1_0_setIdx <= io_write_0_bits_setIdx;
              entries_1_0_entry_valid <= io_write_0_bits_entry_valid;
              entries_1_0_entry_tag <= io_write_0_bits_entry_tag;
              entries_1_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (_GEN_65) begin
          end
          else begin
            entries_1_0_setIdx <= io_write_0_bits_setIdx;
            entries_1_0_entry_valid <= io_write_0_bits_entry_valid;
            entries_1_0_entry_tag <= io_write_0_bits_entry_tag;
            entries_1_0_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
        end
      end
      if (io_write_1_valid & (_GEN_129 | _GEN_121)) begin
        entries_1_1_setIdx <= io_write_1_bits_setIdx;
        entries_1_1_entry_valid <= io_write_1_bits_entry_valid;
        entries_1_1_entry_tag <= io_write_1_bits_entry_tag;
        entries_1_1_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
      end
      else if (io_write_0_valid) begin
        if (_GEN_79) begin
          entries_1_1_setIdx <= io_write_0_bits_setIdx;
          entries_1_1_entry_valid <= io_write_0_bits_entry_valid;
          entries_1_1_entry_tag <= io_write_0_bits_entry_tag;
          entries_1_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        else if (hit) begin
          if (hitNotWritten) begin
            if (_GEN_51) begin
              entries_1_1_setIdx <= io_write_0_bits_setIdx;
              entries_1_1_entry_valid <= io_write_0_bits_entry_valid;
              entries_1_1_entry_tag <= io_write_0_bits_entry_tag;
              entries_1_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (_GEN_66) begin
          end
          else begin
            entries_1_1_setIdx <= io_write_0_bits_setIdx;
            entries_1_1_entry_valid <= io_write_0_bits_entry_valid;
            entries_1_1_entry_tag <= io_write_0_bits_entry_tag;
            entries_1_1_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
        end
      end
      if (io_write_1_valid & (_GEN_130 | _GEN_122)) begin
        entries_1_2_setIdx <= io_write_1_bits_setIdx;
        entries_1_2_entry_valid <= io_write_1_bits_entry_valid;
        entries_1_2_entry_tag <= io_write_1_bits_entry_tag;
        entries_1_2_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
      end
      else if (io_write_0_valid) begin
        if (_GEN_80) begin
          entries_1_2_setIdx <= io_write_0_bits_setIdx;
          entries_1_2_entry_valid <= io_write_0_bits_entry_valid;
          entries_1_2_entry_tag <= io_write_0_bits_entry_tag;
          entries_1_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        else if (hit) begin
          if (hitNotWritten) begin
            if (_GEN_52) begin
              entries_1_2_setIdx <= io_write_0_bits_setIdx;
              entries_1_2_entry_valid <= io_write_0_bits_entry_valid;
              entries_1_2_entry_tag <= io_write_0_bits_entry_tag;
              entries_1_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (_GEN_67) begin
          end
          else begin
            entries_1_2_setIdx <= io_write_0_bits_setIdx;
            entries_1_2_entry_valid <= io_write_0_bits_entry_valid;
            entries_1_2_entry_tag <= io_write_0_bits_entry_tag;
            entries_1_2_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
        end
      end
      if (io_write_1_valid & (_GEN_131 | _GEN_123)) begin
        entries_1_3_setIdx <= io_write_1_bits_setIdx;
        entries_1_3_entry_valid <= io_write_1_bits_entry_valid;
        entries_1_3_entry_tag <= io_write_1_bits_entry_tag;
        entries_1_3_usefulCtr_value <= io_write_1_bits_usefulCtr_value;
      end
      else if (io_write_0_valid) begin
        if (_GEN_81) begin
          entries_1_3_setIdx <= io_write_0_bits_setIdx;
          entries_1_3_entry_valid <= io_write_0_bits_entry_valid;
          entries_1_3_entry_tag <= io_write_0_bits_entry_tag;
          entries_1_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
        end
        else if (hit) begin
          if (hitNotWritten) begin
            if (_GEN_53) begin
              entries_1_3_setIdx <= io_write_0_bits_setIdx;
              entries_1_3_entry_valid <= io_write_0_bits_entry_valid;
              entries_1_3_entry_tag <= io_write_0_bits_entry_tag;
              entries_1_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
            end
          end
          else if (_GEN_68) begin
          end
          else begin
            entries_1_3_setIdx <= io_write_0_bits_setIdx;
            entries_1_3_entry_valid <= io_write_0_bits_entry_valid;
            entries_1_3_entry_tag <= io_write_0_bits_entry_tag;
            entries_1_3_usefulCtr_value <= io_write_0_bits_usefulCtr_value;
          end
        end
      end
      if (io_write_0_valid & ~hit)
        state_reg <=
          {~(writeTouchVec_0_bits[1]),
           writeTouchVec_0_bits[1] ? ~(writeTouchVec_0_bits[0]) : state_reg[1],
           writeTouchVec_0_bits[1] ? state_reg[0] : ~(writeTouchVec_0_bits[0])};
      if (io_write_1_valid & ~hit_1)
        state_reg_1 <=
          {~(writeTouchVec_1_bits[1]),
           writeTouchVec_1_bits[1] ? ~(writeTouchVec_1_bits[0]) : state_reg_1[1],
           writeTouchVec_1_bits[1] ? state_reg_1[0] : ~(writeTouchVec_1_bits[0])};
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:7];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [3:0] i = 4'h0; i < 4'h8; i += 4'h1) begin
          _RANDOM[i[2:0]] = `RANDOM;
        end
        needWrite_0_0 = _RANDOM[3'h0][0];
        needWrite_0_1 = _RANDOM[3'h0][1];
        needWrite_0_2 = _RANDOM[3'h0][2];
        needWrite_0_3 = _RANDOM[3'h0][3];
        needWrite_1_0 = _RANDOM[3'h0][4];
        needWrite_1_1 = _RANDOM[3'h0][5];
        needWrite_1_2 = _RANDOM[3'h0][6];
        needWrite_1_3 = _RANDOM[3'h0][7];
        entries_0_0_setIdx = _RANDOM[3'h0][16:8];
        entries_0_0_entry_valid = _RANDOM[3'h0][17];
        entries_0_0_entry_tag = _RANDOM[3'h0][30:18];
        entries_0_0_entry_takenCtr_value = {_RANDOM[3'h0][31], _RANDOM[3'h1][1:0]};
        entries_0_0_usefulCtr_value = _RANDOM[3'h1][3:2];
        entries_0_1_setIdx = _RANDOM[3'h1][12:4];
        entries_0_1_entry_valid = _RANDOM[3'h1][13];
        entries_0_1_entry_tag = _RANDOM[3'h1][26:14];
        entries_0_1_entry_takenCtr_value = _RANDOM[3'h1][29:27];
        entries_0_1_usefulCtr_value = _RANDOM[3'h1][31:30];
        entries_0_2_setIdx = _RANDOM[3'h2][8:0];
        entries_0_2_entry_valid = _RANDOM[3'h2][9];
        entries_0_2_entry_tag = _RANDOM[3'h2][22:10];
        entries_0_2_entry_takenCtr_value = _RANDOM[3'h2][25:23];
        entries_0_2_usefulCtr_value = _RANDOM[3'h2][27:26];
        entries_0_3_setIdx = {_RANDOM[3'h2][31:28], _RANDOM[3'h3][4:0]};
        entries_0_3_entry_valid = _RANDOM[3'h3][5];
        entries_0_3_entry_tag = _RANDOM[3'h3][18:6];
        entries_0_3_entry_takenCtr_value = _RANDOM[3'h3][21:19];
        entries_0_3_usefulCtr_value = _RANDOM[3'h3][23:22];
        entries_1_0_setIdx = {_RANDOM[3'h3][31:24], _RANDOM[3'h4][0]};
        entries_1_0_entry_valid = _RANDOM[3'h4][1];
        entries_1_0_entry_tag = _RANDOM[3'h4][14:2];
        entries_1_0_entry_takenCtr_value = _RANDOM[3'h4][17:15];
        entries_1_0_usefulCtr_value = _RANDOM[3'h4][19:18];
        entries_1_1_setIdx = _RANDOM[3'h4][28:20];
        entries_1_1_entry_valid = _RANDOM[3'h4][29];
        entries_1_1_entry_tag = {_RANDOM[3'h4][31:30], _RANDOM[3'h5][10:0]};
        entries_1_1_entry_takenCtr_value = _RANDOM[3'h5][13:11];
        entries_1_1_usefulCtr_value = _RANDOM[3'h5][15:14];
        entries_1_2_setIdx = _RANDOM[3'h5][24:16];
        entries_1_2_entry_valid = _RANDOM[3'h5][25];
        entries_1_2_entry_tag = {_RANDOM[3'h5][31:26], _RANDOM[3'h6][6:0]};
        entries_1_2_entry_takenCtr_value = _RANDOM[3'h6][9:7];
        entries_1_2_usefulCtr_value = _RANDOM[3'h6][11:10];
        entries_1_3_setIdx = _RANDOM[3'h6][20:12];
        entries_1_3_entry_valid = _RANDOM[3'h6][21];
        entries_1_3_entry_tag = {_RANDOM[3'h6][31:22], _RANDOM[3'h7][2:0]};
        entries_1_3_entry_takenCtr_value = _RANDOM[3'h7][5:3];
        entries_1_3_usefulCtr_value = _RANDOM[3'h7][7:6];
        valids_0_0 = _RANDOM[3'h7][8];
        valids_0_1 = _RANDOM[3'h7][9];
        valids_0_2 = _RANDOM[3'h7][10];
        valids_0_3 = _RANDOM[3'h7][11];
        valids_1_0 = _RANDOM[3'h7][12];
        valids_1_1 = _RANDOM[3'h7][13];
        valids_1_2 = _RANDOM[3'h7][14];
        valids_1_3 = _RANDOM[3'h7][15];
        state_reg = _RANDOM[3'h7][18:16];
        state_reg_1 = _RANDOM[3'h7][21:19];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        needWrite_0_0 = 1'h0;
        needWrite_0_1 = 1'h0;
        needWrite_0_2 = 1'h0;
        needWrite_0_3 = 1'h0;
        needWrite_1_0 = 1'h0;
        needWrite_1_1 = 1'h0;
        needWrite_1_2 = 1'h0;
        needWrite_1_3 = 1'h0;
        entries_0_0_setIdx = 9'h0;
        entries_0_0_entry_valid = 1'h0;
        entries_0_0_entry_tag = 13'h0;
        entries_0_0_entry_takenCtr_value = 3'h0;
        entries_0_0_usefulCtr_value = 2'h0;
        entries_0_1_setIdx = 9'h0;
        entries_0_1_entry_valid = 1'h0;
        entries_0_1_entry_tag = 13'h0;
        entries_0_1_entry_takenCtr_value = 3'h0;
        entries_0_1_usefulCtr_value = 2'h0;
        entries_0_2_setIdx = 9'h0;
        entries_0_2_entry_valid = 1'h0;
        entries_0_2_entry_tag = 13'h0;
        entries_0_2_entry_takenCtr_value = 3'h0;
        entries_0_2_usefulCtr_value = 2'h0;
        entries_0_3_setIdx = 9'h0;
        entries_0_3_entry_valid = 1'h0;
        entries_0_3_entry_tag = 13'h0;
        entries_0_3_entry_takenCtr_value = 3'h0;
        entries_0_3_usefulCtr_value = 2'h0;
        entries_1_0_setIdx = 9'h0;
        entries_1_0_entry_valid = 1'h0;
        entries_1_0_entry_tag = 13'h0;
        entries_1_0_entry_takenCtr_value = 3'h0;
        entries_1_0_usefulCtr_value = 2'h0;
        entries_1_1_setIdx = 9'h0;
        entries_1_1_entry_valid = 1'h0;
        entries_1_1_entry_tag = 13'h0;
        entries_1_1_entry_takenCtr_value = 3'h0;
        entries_1_1_usefulCtr_value = 2'h0;
        entries_1_2_setIdx = 9'h0;
        entries_1_2_entry_valid = 1'h0;
        entries_1_2_entry_tag = 13'h0;
        entries_1_2_entry_takenCtr_value = 3'h0;
        entries_1_2_usefulCtr_value = 2'h0;
        entries_1_3_setIdx = 9'h0;
        entries_1_3_entry_valid = 1'h0;
        entries_1_3_entry_tag = 13'h0;
        entries_1_3_entry_takenCtr_value = 3'h0;
        entries_1_3_usefulCtr_value = 2'h0;
        valids_0_0 = 1'h0;
        valids_0_1 = 1'h0;
        valids_0_2 = 1'h0;
        valids_0_3 = 1'h0;
        valids_1_0 = 1'h0;
        valids_1_1 = 1'h0;
        valids_1_2 = 1'h0;
        valids_1_3 = 1'h0;
        state_reg = 3'h0;
        state_reg_1 = 3'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_write_0_ready = ~fullVec_0;
  assign io_write_1_ready = ~fullVec_1;
  assign io_read_0_valid = ~emptyVec_0;
  assign io_read_0_bits_setIdx = _GEN_11[readIdx];
  assign io_read_0_bits_entry_valid = _GEN_13[readIdx];
  assign io_read_0_bits_entry_tag = _GEN_15[readIdx];
  assign io_read_0_bits_entry_takenCtr_value = _GEN_17[readIdx];
  assign io_read_0_bits_usefulCtr_value = _GEN_19[readIdx];
  assign io_read_1_valid = ~emptyVec_1;
  assign io_read_1_bits_setIdx = _GEN_10[readIdx_1];
  assign io_read_1_bits_entry_valid = _GEN_12[readIdx_1];
  assign io_read_1_bits_entry_tag = _GEN_14[readIdx_1];
  assign io_read_1_bits_entry_takenCtr_value = _GEN_16[readIdx_1];
  assign io_read_1_bits_usefulCtr_value = _GEN_18[readIdx_1];
endmodule

