// Generated by CIRCT firtool-1.135.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CommonHR(
  input         clock,
  input         reset,
  input         io_stageCtrl_s0_fire,
  input         io_stageCtrl_s3_fire,
  input         io_update_taken,
  input         io_update_condHitMask_0,
  input         io_update_condHitMask_1,
  input         io_update_condHitMask_2,
  input         io_update_condHitMask_3,
  input         io_update_condHitMask_4,
  input         io_update_condHitMask_5,
  input         io_update_condHitMask_6,
  input         io_update_condHitMask_7,
  input  [4:0]  io_update_firstTakenBranch_bits_cfiPosition,
  input  [1:0]  io_update_firstTakenBranch_bits_attribute_branchType,
  input  [4:0]  io_update_position_0,
  input  [4:0]  io_update_position_1,
  input  [4:0]  io_update_position_2,
  input  [4:0]  io_update_position_3,
  input  [4:0]  io_update_position_4,
  input  [4:0]  io_update_position_5,
  input  [4:0]  io_update_position_6,
  input  [4:0]  io_update_position_7,
  input  [48:0] io_update_startPc_addr,
  input  [48:0] io_update_target_addr,
  input         io_redirect_valid,
  input  [48:0] io_redirect_cfiPc_addr,
  input         io_redirect_taken,
  input  [1:0]  io_redirect_attribute_branchType,
  input  [48:0] io_redirect_target_addr,
  input  [15:0] io_redirect_meta_ghr,
  input  [7:0]  io_redirect_meta_bw,
  input         io_redirect_meta_hitMask_0,
  input         io_redirect_meta_hitMask_1,
  input         io_redirect_meta_hitMask_2,
  input         io_redirect_meta_hitMask_3,
  input         io_redirect_meta_hitMask_4,
  input         io_redirect_meta_hitMask_5,
  input         io_redirect_meta_hitMask_6,
  input         io_redirect_meta_hitMask_7,
  input  [1:0]  io_redirect_meta_attribute_0_branchType,
  input  [1:0]  io_redirect_meta_attribute_1_branchType,
  input  [1:0]  io_redirect_meta_attribute_2_branchType,
  input  [1:0]  io_redirect_meta_attribute_3_branchType,
  input  [1:0]  io_redirect_meta_attribute_4_branchType,
  input  [1:0]  io_redirect_meta_attribute_5_branchType,
  input  [1:0]  io_redirect_meta_attribute_6_branchType,
  input  [1:0]  io_redirect_meta_attribute_7_branchType,
  input  [4:0]  io_redirect_meta_position_0,
  input  [4:0]  io_redirect_meta_position_1,
  input  [4:0]  io_redirect_meta_position_2,
  input  [4:0]  io_redirect_meta_position_3,
  input  [4:0]  io_redirect_meta_position_4,
  input  [4:0]  io_redirect_meta_position_5,
  input  [4:0]  io_redirect_meta_position_6,
  input  [4:0]  io_redirect_meta_position_7,
  output        io_s0_commonHR_valid,
  output [15:0] io_s0_commonHR_ghr,
  output [7:0]  io_s0_commonHR_bw,
  output [15:0] io_commonHR_ghr,
  output [7:0]  io_commonHR_bw
);

  wire        _commonHRBuffer_io_enq_ready;
  wire        _commonHRBuffer_io_deq_valid;
  wire        _commonHRBuffer_io_deq_bits_valid;
  wire [15:0] _commonHRBuffer_io_deq_bits_ghr;
  wire [7:0]  _commonHRBuffer_io_deq_bits_bw;
  wire        s3_commonHR_valid = 1'h1;
  wire        r0_commonHR_valid = 1'h0;
  reg  [15:0] commonHR_ghr;
  reg  [7:0]  commonHR_bw;
  wire        s3_hitMask_1 =
    io_update_condHitMask_1
    & ~(io_update_condHitMask_0 & io_update_position_0 == io_update_position_1);
  wire        s3_hitMask_2 =
    io_update_condHitMask_2
    & ~(io_update_condHitMask_1 & io_update_position_1 == io_update_position_2
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_2);
  wire        s3_hitMask_3 =
    io_update_condHitMask_3
    & ~(io_update_condHitMask_2 & io_update_position_2 == io_update_position_3
        | io_update_condHitMask_1 & io_update_position_1 == io_update_position_3
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_3);
  wire        s3_hitMask_4 =
    io_update_condHitMask_4
    & ~(io_update_condHitMask_3 & io_update_position_3 == io_update_position_4
        | io_update_condHitMask_2 & io_update_position_2 == io_update_position_4
        | io_update_condHitMask_1 & io_update_position_1 == io_update_position_4
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_4);
  wire        s3_hitMask_5 =
    io_update_condHitMask_5
    & ~(io_update_condHitMask_4 & io_update_position_4 == io_update_position_5
        | io_update_condHitMask_3 & io_update_position_3 == io_update_position_5
        | io_update_condHitMask_2 & io_update_position_2 == io_update_position_5
        | io_update_condHitMask_1 & io_update_position_1 == io_update_position_5
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_5);
  wire        s3_hitMask_6 =
    io_update_condHitMask_6
    & ~(io_update_condHitMask_5 & io_update_position_5 == io_update_position_6
        | io_update_condHitMask_4 & io_update_position_4 == io_update_position_6
        | io_update_condHitMask_3 & io_update_position_3 == io_update_position_6
        | io_update_condHitMask_2 & io_update_position_2 == io_update_position_6
        | io_update_condHitMask_1 & io_update_position_1 == io_update_position_6
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_6);
  wire        s3_hitMask_7 =
    io_update_condHitMask_7
    & ~(io_update_condHitMask_6 & io_update_position_6 == io_update_position_7
        | io_update_condHitMask_5 & io_update_position_5 == io_update_position_7
        | io_update_condHitMask_4 & io_update_position_4 == io_update_position_7
        | io_update_condHitMask_3 & io_update_position_3 == io_update_position_7
        | io_update_condHitMask_2 & io_update_position_2 == io_update_position_7
        | io_update_condHitMask_1 & io_update_position_1 == io_update_position_7
        | io_update_condHitMask_0 & io_update_position_0 == io_update_position_7);
  wire        s3_lessThanFirstTaken_0 =
    io_update_condHitMask_0
    & io_update_position_0 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_1 =
    s3_hitMask_1 & io_update_position_1 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_2 =
    s3_hitMask_2 & io_update_position_2 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_3 =
    s3_hitMask_3 & io_update_position_3 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_4 =
    s3_hitMask_4 & io_update_position_4 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_5 =
    s3_hitMask_5 & io_update_position_5 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_6 =
    s3_hitMask_6 & io_update_position_6 < io_update_firstTakenBranch_bits_cfiPosition;
  wire        s3_lessThanFirstTaken_7 =
    s3_hitMask_7 & io_update_position_7 < io_update_firstTakenBranch_bits_cfiPosition;
  wire [3:0]  s3_numLess =
    4'({1'h0,
        3'({1'h0, 2'({1'h0, s3_lessThanFirstTaken_0} + {1'h0, s3_lessThanFirstTaken_1})}
           + {1'h0,
              2'({1'h0, s3_lessThanFirstTaken_2} + {1'h0, s3_lessThanFirstTaken_3})})}
       + {1'h0,
          3'({1'h0, 2'({1'h0, s3_lessThanFirstTaken_4} + {1'h0, s3_lessThanFirstTaken_5})}
             + {1'h0,
                2'({1'h0, s3_lessThanFirstTaken_6} + {1'h0, s3_lessThanFirstTaken_7})})});
  wire [3:0]  s3_commonHR_bw_numShift =
    io_update_taken
      ? s3_numLess
      : 4'({1'h0,
            3'({1'h0, 2'({1'h0, io_update_condHitMask_0} + {1'h0, s3_hitMask_1})}
               + {1'h0, 2'({1'h0, s3_hitMask_2} + {1'h0, s3_hitMask_3})})}
           + {1'h0,
              3'({1'h0, 2'({1'h0, s3_hitMask_4} + {1'h0, s3_hitMask_5})}
                 + {1'h0, 2'({1'h0, s3_hitMask_6} + {1'h0, s3_hitMask_7})})});
  wire        _s3_commonHR_bw_T_1 =
    io_update_firstTakenBranch_bits_attribute_branchType == 2'h1 & io_update_taken;
  wire [30:0] _s3_commonHR_ghr_T_3 = {15'h0, commonHR_ghr} << s3_commonHR_bw_numShift;
  wire [15:0] s3_commonHR_ghr =
    _s3_commonHR_bw_T_1
      ? {_s3_commonHR_ghr_T_3[14:0], io_update_taken}
      : _s3_commonHR_ghr_T_3[15:0];
  wire [22:0] _s3_commonHR_bw_T_4 = {15'h0, commonHR_bw} << s3_commonHR_bw_numShift;
  wire [7:0]  s3_commonHR_bw =
    _s3_commonHR_bw_T_1
      ? {_s3_commonHR_bw_T_4[6:0],
         io_update_taken
           & {45'(io_update_startPc_addr[48:4]
                  + {44'h0, io_update_firstTakenBranch_bits_cfiPosition[4]}),
              io_update_firstTakenBranch_bits_cfiPosition[3:0]} > io_update_target_addr}
      : _s3_commonHR_bw_T_4[7:0];
  wire        r0_oldHits_0 =
    io_redirect_meta_hitMask_0 & io_redirect_meta_attribute_0_branchType == 2'h1;
  wire        r0_oldCondHits_1 =
    io_redirect_meta_hitMask_1 & io_redirect_meta_attribute_1_branchType == 2'h1;
  wire        r0_oldCondHits_2 =
    io_redirect_meta_hitMask_2 & io_redirect_meta_attribute_2_branchType == 2'h1;
  wire        r0_oldCondHits_3 =
    io_redirect_meta_hitMask_3 & io_redirect_meta_attribute_3_branchType == 2'h1;
  wire        r0_oldCondHits_4 =
    io_redirect_meta_hitMask_4 & io_redirect_meta_attribute_4_branchType == 2'h1;
  wire        r0_oldCondHits_5 =
    io_redirect_meta_hitMask_5 & io_redirect_meta_attribute_5_branchType == 2'h1;
  wire        r0_oldCondHits_6 =
    io_redirect_meta_hitMask_6 & io_redirect_meta_attribute_6_branchType == 2'h1;
  wire        r0_oldHits_1 =
    r0_oldCondHits_1
    & ~(r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_1);
  wire        r0_oldHits_2 =
    r0_oldCondHits_2
    & ~(r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_2
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_2);
  wire        r0_oldHits_3 =
    r0_oldCondHits_3
    & ~(r0_oldCondHits_2 & io_redirect_meta_position_2 == io_redirect_meta_position_3
        | r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_3
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_3);
  wire        r0_oldHits_4 =
    r0_oldCondHits_4
    & ~(r0_oldCondHits_3 & io_redirect_meta_position_3 == io_redirect_meta_position_4
        | r0_oldCondHits_2 & io_redirect_meta_position_2 == io_redirect_meta_position_4
        | r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_4
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_4);
  wire        r0_oldHits_5 =
    r0_oldCondHits_5
    & ~(r0_oldCondHits_4 & io_redirect_meta_position_4 == io_redirect_meta_position_5
        | r0_oldCondHits_3 & io_redirect_meta_position_3 == io_redirect_meta_position_5
        | r0_oldCondHits_2 & io_redirect_meta_position_2 == io_redirect_meta_position_5
        | r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_5
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_5);
  wire        r0_oldHits_6 =
    r0_oldCondHits_6
    & ~(r0_oldCondHits_5 & io_redirect_meta_position_5 == io_redirect_meta_position_6
        | r0_oldCondHits_4 & io_redirect_meta_position_4 == io_redirect_meta_position_6
        | r0_oldCondHits_3 & io_redirect_meta_position_3 == io_redirect_meta_position_6
        | r0_oldCondHits_2 & io_redirect_meta_position_2 == io_redirect_meta_position_6
        | r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_6
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_6);
  wire        r0_oldHits_7 =
    io_redirect_meta_hitMask_7 & io_redirect_meta_attribute_7_branchType == 2'h1
    & ~(r0_oldCondHits_6 & io_redirect_meta_position_6 == io_redirect_meta_position_7
        | r0_oldCondHits_5 & io_redirect_meta_position_5 == io_redirect_meta_position_7
        | r0_oldCondHits_4 & io_redirect_meta_position_4 == io_redirect_meta_position_7
        | r0_oldCondHits_3 & io_redirect_meta_position_3 == io_redirect_meta_position_7
        | r0_oldCondHits_2 & io_redirect_meta_position_2 == io_redirect_meta_position_7
        | r0_oldCondHits_1 & io_redirect_meta_position_1 == io_redirect_meta_position_7
        | r0_oldHits_0 & io_redirect_meta_position_0 == io_redirect_meta_position_7);
  wire [4:0]  _GEN = {1'h0, io_redirect_cfiPc_addr[3:0]};
  wire        r0_lessThanPc_0 = r0_oldHits_0 & io_redirect_meta_position_0 < _GEN;
  wire        r0_lessThanPc_1 = r0_oldHits_1 & io_redirect_meta_position_1 < _GEN;
  wire        r0_lessThanPc_2 = r0_oldHits_2 & io_redirect_meta_position_2 < _GEN;
  wire        r0_lessThanPc_3 = r0_oldHits_3 & io_redirect_meta_position_3 < _GEN;
  wire        r0_lessThanPc_4 = r0_oldHits_4 & io_redirect_meta_position_4 < _GEN;
  wire        r0_lessThanPc_5 = r0_oldHits_5 & io_redirect_meta_position_5 < _GEN;
  wire        r0_lessThanPc_6 = r0_oldHits_6 & io_redirect_meta_position_6 < _GEN;
  wire        r0_lessThanPc_7 = r0_oldHits_7 & io_redirect_meta_position_7 < _GEN;
  wire [3:0]  r0_numLess =
    4'({1'h0,
        3'({1'h0, 2'({1'h0, r0_lessThanPc_0} + {1'h0, r0_lessThanPc_1})}
           + {1'h0, 2'({1'h0, r0_lessThanPc_2} + {1'h0, r0_lessThanPc_3})})}
       + {1'h0,
          3'({1'h0, 2'({1'h0, r0_lessThanPc_4} + {1'h0, r0_lessThanPc_5})}
             + {1'h0, 2'({1'h0, r0_lessThanPc_6} + {1'h0, r0_lessThanPc_7})})});
  wire [3:0]  r0_commonHR_bw_numShift =
    io_redirect_taken
      ? r0_numLess
      : 4'({1'h0,
            3'({1'h0, 2'({1'h0, r0_oldHits_0} + {1'h0, r0_oldHits_1})}
               + {1'h0, 2'({1'h0, r0_oldHits_2} + {1'h0, r0_oldHits_3})})}
           + {1'h0,
              3'({1'h0, 2'({1'h0, r0_oldHits_4} + {1'h0, r0_oldHits_5})}
                 + {1'h0, 2'({1'h0, r0_oldHits_6} + {1'h0, r0_oldHits_7})})});
  wire        _r0_commonHR_bw_T_1 =
    io_redirect_attribute_branchType == 2'h1 & io_redirect_taken;
  wire [30:0] _r0_commonHR_ghr_T_3 =
    {15'h0, io_redirect_meta_ghr} << r0_commonHR_bw_numShift;
  wire [15:0] r0_commonHR_ghr =
    _r0_commonHR_bw_T_1
      ? {_r0_commonHR_ghr_T_3[14:0], io_redirect_taken}
      : _r0_commonHR_ghr_T_3[15:0];
  wire [22:0] _r0_commonHR_bw_T_4 =
    {15'h0, io_redirect_meta_bw} << r0_commonHR_bw_numShift;
  wire [7:0]  r0_commonHR_bw =
    _r0_commonHR_bw_T_1
      ? {_r0_commonHR_bw_T_4[6:0],
         io_redirect_cfiPc_addr > io_redirect_target_addr & io_redirect_taken}
      : _r0_commonHR_bw_T_4[7:0];
  wire        _GEN_0 = io_stageCtrl_s3_fire & ~_commonHRBuffer_io_enq_ready;
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (_GEN_0 & ~reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $fwrite(32'h80000002, "Assertion failed at LogUtils.scala:132\n");
        if (`STOP_COND_)
          xs_assert_v2(`__FILE__, `__LINE__);
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _s0_commonHR_T = io_stageCtrl_s0_fire & _commonHRBuffer_io_deq_valid;
  wire [7:0]  s3_lessThanFirstTakenUInt =
    {s3_lessThanFirstTaken_7,
     s3_lessThanFirstTaken_6,
     s3_lessThanFirstTaken_5,
     s3_lessThanFirstTaken_4,
     s3_lessThanFirstTaken_3,
     s3_lessThanFirstTaken_2,
     s3_lessThanFirstTaken_1,
     s3_lessThanFirstTaken_0};
  wire [7:0]  r0_lessThanPcUInt =
    {r0_lessThanPc_7,
     r0_lessThanPc_6,
     r0_lessThanPc_5,
     r0_lessThanPc_4,
     r0_lessThanPc_3,
     r0_lessThanPc_2,
     r0_lessThanPc_1,
     r0_lessThanPc_0};
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      commonHR_ghr <= 16'h0;
      commonHR_bw <= 8'h0;
    end
    else if (io_redirect_valid) begin
      commonHR_ghr <= r0_commonHR_ghr;
      commonHR_bw <= r0_commonHR_bw;
    end
    else if (io_stageCtrl_s3_fire) begin
      commonHR_ghr <= s3_commonHR_ghr;
      commonHR_bw <= s3_commonHR_bw;
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        commonHR_ghr = _RANDOM[/*Zero width*/ 1'b0][16:1];
        commonHR_bw = _RANDOM[/*Zero width*/ 1'b0][24:17];
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        commonHR_ghr = 16'h0;
        commonHR_bw = 8'h0;
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue2_CommonHREntry commonHRBuffer (
    .clock             (clock),
    .reset             (reset),
    .io_enq_ready      (_commonHRBuffer_io_enq_ready),
    .io_enq_valid      (io_stageCtrl_s3_fire),
    .io_enq_bits_valid (s3_commonHR_valid),
    .io_enq_bits_ghr   (s3_commonHR_ghr),
    .io_enq_bits_bw    (s3_commonHR_bw),
    .io_deq_ready      (io_stageCtrl_s0_fire),
    .io_deq_valid      (_commonHRBuffer_io_deq_valid),
    .io_deq_bits_valid (_commonHRBuffer_io_deq_bits_valid),
    .io_deq_bits_ghr   (_commonHRBuffer_io_deq_bits_ghr),
    .io_deq_bits_bw    (_commonHRBuffer_io_deq_bits_bw),
    .io_flush          (io_redirect_valid)
  );
  assign io_s0_commonHR_valid =
    io_redirect_valid
      ? r0_commonHR_valid
      : _s0_commonHR_T & _commonHRBuffer_io_deq_bits_valid;
  assign io_s0_commonHR_ghr =
    io_redirect_valid
      ? r0_commonHR_ghr
      : _s0_commonHR_T ? _commonHRBuffer_io_deq_bits_ghr : 16'h0;
  assign io_s0_commonHR_bw =
    io_redirect_valid
      ? r0_commonHR_bw
      : _s0_commonHR_T ? _commonHRBuffer_io_deq_bits_bw : 8'h0;
  assign io_commonHR_ghr = commonHR_ghr;
  assign io_commonHR_bw = commonHR_bw;
endmodule

